# Página Legal {.unnumbered}

Gustavo Petro Urrego

Presidente de la República

Javier Pava Sánchez

Director General



Unidad Nacional para la Gestión del Riesgo de Desastres - UNGRD



Oscar Goyeneche Durán

Subdirector General

Diana Mireya Parra Cardona

Secretario General

Sandra Sotomonte Nopssa

Subdirectora para el Conocimiento del Riesgo



Comisión Nacional Asesora para la Investigación en Gestión del Riesgo de Desastres (CNAIGRD)



EDITORES



Sandra Sotomonte Nopssa, Unidad Nacional para la Gestión del Riesgo de Desastres (UNGRD)

Dorotea Cardona Hernández, Instituto de Investigación de Recursos Biológicos Alexander von Humboldt



Omar Joaquín Agudelo, Universidad Nacional de Colombia



Martha Cecilia Cadena, Instituto de Hidrología, Meteorología y Estudios Ambientales (IDEAM)

Carlos Arturo Garcia Ocampo, Universidad del Quindío, representante universidades públicas

William Oswaldo Gaviria Gutierrez, Universidad de Manizales, Red de universitarios de América Latina

y el Caribe para la gestión y la reducción de riesgos de emergencias y desastres (REDULAC/RRD Cap. Colombia)



Enrique Bolívar Guzmán, Ministerio de Educación Nacional (Mineducación)

Jhon Makario Londoño Bonilla, Servicio Geológico Colombiano (SGC)

Juan Leonardo Moreno Rincón, Dirección General Marítima (DIMAR)

Zoraida Piedrahita Calle, Ministerio de Ambiente y Desarrollo Sostenible (Minambiente)

Argiro Ramírez Aristizabal, Ministerio de Ciencia, Tecnología e Innovación (Minciencias)

Alfonso Mariano Ramos Cañon, Universidad Nacional de Colombia, Pontificia Universidad Javeriana,



representante universidades privadas



Leonor Aydé Rodríguez Rojas, Instituto Geográfico Agustín Codazzi (IGAC)



Coordinación editorial

Mauricio Romero Torres

Supervisión

Luisa Cadena Amado

Diseño editorial

Iván Merchán Rodríguez

Proceso de arbitraje



Revisión por pares doble ciega para cada capítulo



Proceso editorial



Guía básica de procesos editoriales, 2018, Editorial UNAL; APA 4a ed; SSF-CSE 8a ed.



ISBN obra digital: 978-958-5509-27-6



Copyright: © Unidad Nacional para la Gestión del Riesgo de Desastres, abril de 2023. Bogotá, Colombia

Todos los derechos reservados. Excepto si se señala otra cosa, la licencia del ítem se describe como Atribución.



NoComercial-SinDerivadas 2.5 Colombia

Distribución gratuita – versión digital