# Prólogo {.unnumbered}

Los desastres no son naturales. Afirmación categórica expresada en el prólogo a la primera edición de este libro y que deseamos sostener en las reflexiones actuales. No podemos olvidar el tortuoso camino recorrido para llegar a esta. Miles de padres y madres cuyos hijos e hijas ahora hacen parte del recuerdo. Miles de hijos e hijas cuyos padres y madres están ahora en un espacio privilegiado de la memoria. Sus partidas no estaban asociadas a la finalización esperada del curso de la vida, se dieron, porque como humanidad, hicimos o dejamos de hacer, todo lo necesario para que la muerte llegara con prontitud.

Reconocer el desastre como construcción psicosocial, política, cultural y económica, de base implica asumir la responsabilidad del adiós prematuro, la complicidad con la lágrima asociada al dolor, la obligación de reconocernos artífices del sufrimiento y el encadenamiento innegable con los cuerpos cuyas vibraciones ya no están en este mundo, que dieron sus últimos suspiros bajo un alud de tierra, una inundación o un colapso estructural.

Entender el desastre como una consecuencia de la acción humana nos acerca a los cuerpos físicos, simbólicos, sociales y psicológicos mutilados, bien sean los propios o ajenos. Esta transformación en la cotidianidad de la vida, la hemos venido leyendo como impactos, aunque las gramáticas usadas para ello enmudecen las estéticas de la existencia. Proyectamos con base en los lenguajes de Enío, así, calculamos la pérdida por millones de muertes, cosechas, viviendas, vías, dólares, vehículos, estructuras. La escritura del desastre deviene en las letras de la pérdida y somos, como humanidad, los autores y autoras de ello.

“¡No más minutos de silencio por los muertos!. No más horas de silencio. No más meses de silencio: de ahora en adelante por cada muerto un grito que le desgarre los oídos a la muerte”, esto escribía Gustavo Wilches-Chaux en 1987; ese grito que tenía por propósito dejar la muerte sorda, constituía un llamado para nuestra sociedad. Era un grito para nosotros, para dejar de matarnos y culpar la naturaleza por la ausencia. Un grito para dejar de hablar de “desastres naturales” y entender que el desastre tiene, en sus causas, todo de humano y nada de natural.

Nos gritamos como sociedad colombiana al ver los cuerpos bañados en polvo y las calles pintadas de sangre durante el desastre ocurrido en 1999 que implicó para el municipio de Armenia una reconstrucción casi total. Volvimos a gritar durante 2010 y 2011 cuando compatriotas sintieron la evanescencia de sus vidas cobijadas por el agua. Gritamos una vez más en 2017 cuando, por varias horas, el estridente silencio del lodo enmudeció el maguaré. Gritamos y lo seguimos haciendo por los desastres de la vida cotidiana, que entre las grandes cifras de los informes de gestión parecen quedar ocultos. Silenciar el desastre implica como país escucharnos de formas otras.

Como línea de fuga para configurar relaciones otras de escucha se edifica la Política Nacional para la Gestión del Riesgo de Desastre en Colombia (Ley 1523 de 2012). Ello implica un hito para el país, especialmente porque se establecen un conjunto de principios de interacción orientados al reconocimiento, invitación al diálogo y trabajo conjunto entre todos los habitantes del territorio. Si somos constructores de muerte, sin duda alguna podemos ser constructores de vida. Con ello se busca construir un marco de sentido permitiendo que las diferencias territoriales configuren capacidades de acción conjunta y situada.

Esta articulación de capacidades es posible en la medida que nos reconozcamos como territorio e identifiquemos como se va transformando el mismo (Principio de oportuna información). Asumamos la amplitud de nuestras voces, señas, símbolos y signos como elemento privilegiado para la transformación de nuestra realidad (Principio participativo). Nos encontremos en la diferencia y heterogeneidad de saberes. No existe un saber más valioso que el otro, todos permiten la construcción de realidad (Principio de diversidad cultural). La naturaleza no humana configura un actor de amplia importancia en el territorio, su silenciamiento o desconocimiento es una forma de violencia que debe ser erradicada (Principio de sostenibilidad ambiental).

Así, la armonización de los principios mencionados y los once restantes, marcan un horizonte para dejar atrás la letra muerta del desastre y constituir letra viva en la gestión del riesgo. Esto, querido lector, querida lectora lo encontrarás en el presente libro. Navegarás entre las lecciones aprendidas del dolor vivido en Armenia, la defensa de todas las formas de existencia y devenir en ethos respetuoso a través de la gestión integral de la biodiversidad y las soluciones basadas en la naturaleza. Te encontrarás con los estilos de afrontamiento que tienen los bomberos voluntarios en Quindío y la configuración de mundos posibles de comunidades en La Mojana.

Recorrerás las preguntas por el agua en Bogotá D.C. Guapi y Antioquia, así como los avatares del fuego en la Orinoquía. Transitarás el pasado en nota de presente potencial al revisar lo sucedido en Armero y Mocoa. Te encontrarás con los campesinos de nuestro país y su llamado a una Gestión del Riesgo de Desastres con enfoque diferencial. Estarás en Colombia y sus preguntas contextuadas, todas ellas centradas en la apuesta por una vida digna y una digna vida.

Entendemos la investigación no como un acto neutro, sino como un proceso que tiene una apuesta ético-política clara. Investigamos, con el propósito explícito de contribuir a la seguridad, el bienestar, la calidad de vida de las personas y al desarrollo sostenible, tal como lo indica el artículo 1 de nuestra política nacional en gestión del riesgo. Por ello, para la Comisión Nacional Asesora para la Investigación en Gestión del Riesgo de Desastres, a través de nosotros como sus representantes, es un honor disponer ante ti el presente libro. Asumimos, el camino para un país sin desastres se va construyendo día a día, pero los pasos hay que darlos con prontitud. 

**Leonor Ayde Rodriguez Rojas**

Profesional especializado

Dirección de Investigación y Prospectiva

Instituto Geográfico Agustín Codazzi

**William Oswaldo Gaviria Gutiérrez**

Docente - Investigador

Universidad de Manizales

Integrante

Red Universitaria de las Américas y el Caribe para la Reducción del Riesgo de Desastres

REDULAC/RRD Capítulo Colombia

