---
title: "Capítulo 09: Gestión del riesgo de desastres en Colombia: una mirada diferencial para los campesinos y su vida digna"
author:
  - "Sandra Eliana Alzate Vargas"
  - "Sandra Patricia Duque Quintero"
title-block-banner: "images/banner_2023.png"
---

1 Facultad de Derecho y Ciencias Políticas, Grupo Estudios de Derecho y Política. Universidad de Antioquia, calle 70 No. 52 – 21, Medellín, Colombia

*Autor de contacto: Sandra Eliana Alzate Vargas, Facultad de Derecho y Ciencias Políticas, Grupo Estudios de Derecho y Política. Universidad de Antioquia, calle 70 No. 52 – 21, Medellín, Colombia. Correo-e: ,  

## Resumen {.unnumbered}

La gestión del riesgo de desastres es un proceso social que además de los aspectos técnicos, debe incorporar factores sociales, económicos y culturales como la pobreza y la marginalidad social. Estos factores inciden en la configuración de la vulnerabilidad y por ende del riesgo, agravando las consecuencias devastadoras de los desastres. Para dar respuesta a las reales necesidades de las poblaciones expuestas y afectadas, la gestión del riesgo debe entender sus características culturales, sociales y económicas, de modo que las intervenciones propuestas mitiguen o prevengan el riesgo. Considerando que los campesinos son una de las poblaciones con mayor grado de vulnerabilidad debido a sus precarias condiciones de vida y marginalidad, en este capítulo se aborda primero, la gestión del riesgo de desastres como un proceso técnico, científico, social y se establece un punto de intersección con el derecho a la vida digna de los campesinos. Segundo, se describen los conceptos de enfoque diferencial y del concepto *campesino*. La metodología implementada es cualitativa con enfoque hermenéutico, en el capítulo se presentan los resultados del primer momento de la metodología referido al análisis textual donde la pregunta de investigación, como proyecto de sentido, permite conversar con los textos-literatura especializada. El método permitió identificar el alto grado de vulnerabilidad de los campesinos. Finalmente, se concluye que es necesario incorporar en la gestión del riesgo de desastres, una mirada diferenciadora de los campesinos, lo que posibilitará unas mejores condiciones de existencia y bienestar y, por consiguiente, la concreción en la práctica de su derecho a la vida digna. Finalmente, se recomienda iniciar con la recolección de información específica para esta población.

**Palabras clave:** gestión del riesgo de desastres, desastres socio-naturales, campesinos, enfoque diferencial, vida digna.

## Abstract {.unnumbered}

**Disaster risk management in Colombia: a necessary differential view for the dignified life of farmers**

Disaster risk management is a social process that, in addition to the technical aspects of the threat, incorporates socio-economic and cultural factors such as poverty and social marginality. These factors influence the configuration of vulnerability and risk, aggravating the devastating consequences of disasters. To respond to the real needs of the populations exposed and affected, risk management must understand their own cultural, social, and economic characteristics, so that the proposed interventions mitigate or prevent the risk. Considering that one of the populations that presents a greater degree of exposure and vulnerability are the farmers, due to their precarious living conditions and the marginality in which they find themselves; this chapter first deals with an analysis of the management of the disaster risk and it is described as besides being a technical-scientific process, it is also a social process and, to that extent, a point of intersection is established with the right to a dignified life of farmers. In a second moment, it described the farmers' concept and its necessary recognition as a differentiated subject in disaster risk management. The methodology implemented is qualitative with a hermeneutical approach. The chapter shows the results of the first moment of the methodology, which is indicated to textual analysis, where the research question, as a project of meaning, allows conversation with the texts -specialized literature. The method allowed them to identify the farmers' high degree of exposure and vulnerability. It is concluded that it is necessary to incorporate in disaster risk management a differentiating view of farmers as a group of special protection by law, which will enable better conditions of existence and well-being and realize their right to a dignified life. Finally, it is recommended to start by recollecting specific information about this population.

**Keywords**: Disaster risk management, socio-natural disasters, farmers, differential approach, dignified life

## INTRODUCCIÓN

La mayor extensión del territorio colombiano corresponde a suelo rural [1]. El 22.9% de la población nacional es rural, de la cual el 15.8% es población rural dispersa y el restante 7.1% habita en alguno de los 6,896 centros poblados rurales. El 30.22% de población rural dispersa vive con necesidades básicas insatisfechas (NBI) y el 10.51% viven en la miseria con deficiencias significativas de vivienda, prestación de servicios públicos, asistencia en salud y dependencia económica. Estos porcentajes aumentan a nivel regional porque el desarrollo regional ha sido desequilibrado, y las poblaciones rurales más alejadas de los centros urbanos de poder económico y político presentan cifras alarmantes en las condiciones de pobreza y marginalidad. Por ejemplo, en Antioquia el porcentaje de personas rurales con NBI es del 26.77%, en Chocó de 62.58%, y en Vaupés de 86.17%. Del mismo modo ocurre con los porcentajes de población rural en la miseria, que en Antioquia corresponden al 9.13% de la población, en Chocó al 30.35%, y en Vaupés al 58.27% [1]. 

Es necesario precisar, que la población campesina está inmersa tanto en la población de centros poblados rurales como en el área rural dispersa, representando la mayoría de dicha población. Al respecto, según la Encuesta Nacional de Calidad de Vida 2019 (ECV) [2], el 84.8% de la población de centros poblados y rural dispersa se reconoce como campesina, así como el 84.7% de los hogares. En cuanto a las NBI de esta población, el 35.4% de los hogares campesinos tiene incidencia de pobreza multidimensional y el 65.4% de los jefes de hogar campesino se perciben como pobres [2]. Es importante anotar que dicha información se discrimina para los campesinos sólo a partir del año 2020, y no se tienen registros diferenciados de censos o encuestas de calidad de vida anteriores.


::: {.caja-box}
**Caja 1.** Encuesta de calidad de vida (ECV) La ECV es una operación estadística que el Departamento Administrativo Nacional de Estadística (DANE) realiza con el objeto de recoger información sobre diferentes aspectos y dimensiones del bienestar y las condiciones de vida de los hogares, incluyendo temas como el acceso a bienes y servicios públicos, privados o comunales, salud, educación, atención integral de niños y niñas menores de 5 años, entre otros. La consideración de estos aspectos hace posible realizar posteriores análisis a los factores que explican los diferentes niveles de vida existentes en la sociedad. La ECV es, además, la fuente de información del cálculo del Índice de Pobreza Multidimensional (IPM) [3].

:::

Los índices de pobreza multidimensional de los hogares campesinos encontrados por el DANE [2] como analfabetismo 18%, bajo logro educativo 70.4%, desempleo de larga duración 11.5%, trabajo informal 86.7%, y hacinamiento crítico 8.9% develan la existencia de condiciones de vulnerabilidad y de vulneración de los campesinos en Colombia. Los datos confirman que los campesinos en Colombia son una población poco abordada desde la mirada de la gestión del riesgo de desastres, siendo un grupo social que ocupa sectores rurales que los hacen vulnerables a mayores consecuencias en el momento de la ocurrencia de un desastre. Este desconocimiento hace que esta población pueda ser excluida y marginada cuando se realizan las políticas públicas [4] (ver **Fig. 1**).

**Figura 1.** Algunos datos sobre los campesinos en Colombia. Fuente: Censo Nacional de Población y Vivienda, 2018 [1] y Encuesta Nacional de Calidad de Vida de 2019 [2]. Elaboración propia utilizando la APP Canva.

Se reconoce que la situación de vulnerabilidad y exclusión de los campesinos ha pasado desapercibida para el resto de la sociedad, lo que los sitúa en unas condiciones de mayor debilidad y fragilidad que al resto de la población [4]. A la precariedad en las condiciones de vida de los campesinos identificadas por el DANE y reconocidas por los mismos campesinos en la ECV 2019 [2], se suma la existencia de constantes amenazas y riesgos de desastres socio-naturales en el territorio, tales como movimientos en masa, inundaciones, avenidas torrenciales, e incendios forestales [5,6] que eventualmente agravan su situación de precariedad tornando indigna su vida [4].


::: {.caja-box}
**Caja 2.** Derecho a una vida digna de los campesinos en Colombia desde una noción aspiracional  La dignidad de la vida es un concepto amplio que incluye elementos de dignidad humana como no sufrir tratos crueles o degradantes, de calidad de vida como tener acceso a una vivienda o al agua potable, y elementos aspiracionales propios de la capacidad de los seres humanos de soñar con un mundo mejor. La noción aspiracional de vida digna para los campesinos tiene cuatro elementos [4]:  La aspiración al reconocimiento político de los campesinos y campesinas, que implica la aceptación de la validez de la economía campesina como modelo alternativo de desarrollo.  La aspiración a que se respete la vida y los derechos humanos.  La aspiración a formas de interacción social y económica solidarias centradas en la cooperación y el respeto, más que en la competencia.  La aspiración a un relacionamiento más armónico con la naturaleza.

:::

En Colombia, el 84.7% de la población y el 86.6% de los activos, habitan o se localizan en áreas expuestas a dos o más amenazas naturales [5]. Según datos del Sistema de Inventario de Desastres (DesInventar) [7], durante 2017 se presentaron 2,972 eventos, que reportaron 610 muertos, 1,234 heridos, 109 desaparecidos, 1,568 casas destruidas y 30,899 casas afectadas. Datos más recientes indican que entre el 16 de marzo y el 6 de abril de 2022, se produjeron 202 eventos meteorológicos en 131 municipios de 17 departamentos del país. En total 9,100 personas resultaron afectadas, 14 personas murieron y 28 resultaron heridas. En cuanto a los daños, 1,151 viviendas resultaron afectadas y 39 fueron destruidas. [8]. Los datos indican altos índices de riesgo y amenaza [9], lo que asociado a las condiciones de alta marginalidad de los campesinos contribuye a incrementar su vulnerabilidad y la de sus bienes aumentando los impactos y el potencial destructor de estos eventos. 

En consonancia con lo anterior, la pobreza y exclusión social son factores determinantes de los niveles de vulnerabilidad de las personas frente a los desastres socio-naturales [10,11,12,13]. Igualmente, se resalta que los desastres socio - naturales y el cambio climático están asociados a la vulnerabilidad social, regional y sectorial de las comunidades [14] y se reconoce que reducen el bienestar de la población y aumentan la pobreza [15]. En una relación bidireccional la pobreza aumenta la vulnerabilidad socioeconómica y física, pero a su vez, la ocurrencia de un desastre empobrece a la población afectada. Existe una relación entre el riesgo medioambiental y la pobreza, ya que este es un factor que incide directamente en la vulnerabilidad afectando la vivienda, el ingreso y la salud en este sentido la vulnerabilidad y la pobreza están estrechamente relacionadas [16].

De otro lado, la situación de especial fragilidad de la población campesina está asociada a un modelo de desarrollo rural ineficiente con características que lo convierten en un factor de alto deterioro del ambiente y la biodiversidad, que no promueve el desarrollo humano y que hace a la población rural más vulnerada y vulnerable [17].

Esta vulnerabilidad manifiesta de los campesinos en la dignidad de su vida, se refleja y acrecienta por la inexistencia de políticas nacionales de gestión del riesgo y de gestión ambiental con énfasis rural que reconozcan sus especificidades territoriales y culturales [17]. Aunque los fenómenos naturales no tienen fronteras político-administrativas, las políticas públicas tienen un enfoque hacia lo urbano, desconociendo así la magnitud devastadora que los desastres tienen para los campesinos, ya que sus condiciones de vida están muy por debajo de las condiciones de la población urbana [18].

La conjunción de altos niveles de vulnerabilidad y exposición a desastres, implica una afectación a su derecho fundamental a una vida digna, que en el caso de los campesinos, además de afectar su integridad física y sus medios de existencia, rompe su especial relación con la tierra y con la naturaleza, sus redes de apoyo comunitario y su forma de trabajo familiar forzándolos en muchos casos a desplazarse a otros territorios y a vincularse a los circuitos económicos comerciales y al trabajo asalariado, desestructurando su forma de vida campesina [4]. Ante este panorama, se hace imperativo que la gestión del riesgo de desastres, reconozca la vulnerabilidad de los campesinos y su derecho fundamental a gozar de una vida en condiciones dignas y a respetar su identidad campesina para lo cual se propone desde el saber jurídico la incorporación en la gestión del riesgo de desastres de un enfoque diferencial que permita el reconocimiento de la identidad propio del sujeto campesino y su derecho a la vida digna.

En este capítulo se pretende mostrar que incorporar una mirada diferenciadora en la gestión del riesgo de desastres de los campesinos posibilita unas mejores condiciones de existencia y bienestar y por consiguiente la concreción en la práctica del derecho a la vida digna para esta población.

## LA GESTIÓN DEL RIESGO DE DESASTRES COMO PROCESO SOCIAL

La categoría riesgo de desastres de origen natural y socio-natural se ha investigado ampliamente desde distintas áreas del conocimiento, especialmente desde la geología [18], la ingeniería [10, 19], y desde algunas ciencias sociales como la sociología [20], también desde las teorías del desarrollo [14,15, 21] o la geografía [10,18]. En contraste, el derecho poco se ha ocupado del estudio del riesgo, más allá de la creación de legislación para regular los seguros o la conformación y funcionamiento de organismos de socorro. En Colombia, apenas desde 2012 se creó una política pública de gestión del riesgo de desastres que trasciende los aspectos de intervención en el desastre y post-desastre, para ocuparse de la reducción y mitigación de estos [22].

La evolución teórica y conceptual de la gestión del riesgo de desastres ha sido globalmente muy dinámica y existe un consenso de la relación entre los desastres con las condiciones sociales de las poblaciones [11]. Así mismo, que para establecer las características y la magnitud del riesgo es necesario considerar que las condiciones sociales son amplificadores del mismo [23].

De ahí se entiende al riesgo como un fenómeno de origen natural o antrópico que altera el medio ambiente ocupado por una comunidad vulnerable [13], que también se define “como la probabilidad de pérdidas futuras, que es el resultado de existencia de un peligro latente asociado con la posibilidad de que se presenten fenómenos peligrosos y de unas características propias o intrínsecas de la sociedad que la predisponen a sufrir daños en diversos grados” [10, p.21].

Por su parte, el Comité Nacional para el Conocimiento del Riesgo del Sistema Nacional de Gestión del Riesgo de Desastres (SNGRD) reconoce el riesgo como “Un proceso construido en el tiempo por la sociedad y en consecuencia se define la Gestión del Riesgo de Desastres (GRD) como un proceso social. Se reconoce además que los desastres no son naturales, y que por el contrario existen factores políticos, sociales y culturales que inciden en el grado de vulnerabilidad de los individuos al momento de enfrentar y recuperarse de la ocurrencia de un evento físico” [24, p.21].

Estas definiciones parten de reconocer la relación bidireccional existente entre los desastres y las condiciones sociales, económicas y políticas de las poblaciones amenazadas o afectadas. A partir de las misma, es evidente que en Colombia en las áreas rurales, la marginalidad y los altos niveles de pobreza contribuyen a incrementar la vulnerabilidad de las poblaciones y sus bienes, y se identifica que los campesinos son un grupo altamente expuesto y vulnerable frente a los desastres socio-naturales.

Así, desde un necesario reconocimiento del derecho que todos tenemos a una vida digna, es fundamental considerar el riesgo no sólo como de origen natural, sino también, como un concepto social, consecuencia de un modelo de desarrollo económico y ambiental insostenible [6,19]. Esto implica que el riesgo está dado por la amenaza, pero también incorpora factores socioeconómicos y culturales que se expresan en un mayor o menor grado de exposición de las personas y sus bienes. En este sentido, existen enfoques como los descritos, que asocian la pobreza a la vulnerabilidad y que incluyen la pobreza como uno de los factores que definen el riesgo, indicando que a mayor pobreza se incrementa la vulnerabilidad [13, 16].

En el caso colombiano, el enfoque de análisis de la vulnerabilidad en su relación estrecha con la pobreza y con el desarrollo económico, es sustentado, entre otros por Villareal Camacho [19] quien señala que existe una relación causa-efecto entre desastres y pobreza, la cual se profundiza por el contexto de cambio climático. Así mismo, se plantea que cubrir las necesidades básicas de la población reduce el impacto y ocurrencia de desastres; no obstante, estar por encima de los niveles mínimos de calidad de vida no es suficiente para reducir el riesgo y puede llevar a configurar escenarios de vulnerabilidad [25]. Otra forma de expresarlo es con la ecuación: pobreza/riesgo medioambiental = problema de desarrollo [16, p.127]. Desde el derecho, “la vulnerabilidad debe entenderse como la falta de recursos económicos, y lo que es más importante, como la falta permanente de derechos políticos y sociales” [15, p.127]. 

En tanto, en el *Global Assessment Report on Disaster Risk Reduction* (GAR) [26] en el mismo sentido, se concluye que la relación entre el riesgo de desastre y el desarrollo es clara y que la incorporación de la reducción del riesgo de desastres en la planificación del desarrollo y en los presupuestos para impulsarlo, es ciertamente un indicador de desarrollo insostenible.

Por consiguiente, la gestión del riesgo de desastres se configura como una estrategia fundamental para el desarrollo, incluyendo la adaptación al cambio climático, coadyuvando a que éste sea sostenible desde el punto de vista ambiental y también como un desarrollo seguro. Pasando de enfoques restauradores post-evento a enfoques preventivos, y a la inclusión en todos sus procesos (conocimiento del riesgo, reducción del riesgo y manejo de desastres) de acciones diferenciadoras de los distintos sujetos damnificados por los desastres. 

## EL ENFOQUE DIFERENCIAL EN LA GESTIÓN DEL RIESGO DE DESASTRES

El enfoque diferencial hace referencia a la necesidad de establecer un trato diferente a grupos de población que están en una situación de mayor vulnerabilidad en razón de sus condiciones propias como de etnia, género, edad, orientación sexual o discapacidad, lo cual requiere la adopción de medidas que permitan superar esa vulnerabilidad. Conceptualmente se entiende el enfoque diferencial como un proceso político en el que se afirman derechos identitarios y consiste en reivindicar y conceder derechos jurídicos, políticos, sociales y culturales a poblaciones históricamente marginadas [27].

Para que la gestión del riesgo de desastres incorpore el enfoque diferencial y a partir de este implementar acciones diferenciadoras, es necesario revisar la forma en que se recolecta la información de los desastres y sus efectos, la cual además de dirigirse a entender las dinámicas de los desastres, debe permitir resolver preguntas técnicas como ¿qué factores inciden en la ocurrencia de los eventos?, ¿quiénes son los damnificados por los desastres? o ¿cuáles pérdidas se generan?, así como preguntas socio-culturales que posibiliten identificar elementos culturales que reducen o incrementan la vulnerabilidad. 

Otra característica de la problemática asociada a la recolección de la información discriminada, viene dada por el énfasis primordialmente urbano de la política de gestión del riesgo de desastres según grupos sociales. Así, el artículo 81 de la Ley 1523 de 2012 establece que el gobierno nacional podrá promover, ejecutar y financiar proyectos de “desarrollo urbano” para efectos de reubicación de asentamientos y de viviendas, mientras que frente a la posibilidad de desarrollar viviendas rurales para procesos de reubicación no hay mención alguna. Esta característica se manifiesta también en el hecho de que los conceptos se expresan en términos urbanos y en que el énfasis de los estudios se dirige a las problemáticas urbanas. 

La Ley 1523 de 2012 está pensada para lo urbano, con fundamento en que las áreas urbanas tienen una mayor concentración de población, lo que potencia los impactos. Sin embargo, analizando los datos de DesInventar 2003, se determina que sólo el 30% de los desastres se localizan en ciudades [28]. De esta manera, puede observarse que desde la política nacional no hay un enfoque específico para lo rural, tampoco para los campesinos a pesar de su vulnerabilidad. Por consiguiente, es necesaria una re-significación del concepto riesgo de desastre que incluya una mirada diferencial para las comunidades campesinas en el país. 

## El CAMPESINO Y SU NECESARIO RECONOCIMIENTO COMO SUJETO DIFERENCIADO EN LA GESTIÓN DEL RIESGO DE DESASTRES

A continuación, se desarrolla el concepto de *campesino* como un primer aporte a la configuración de este grupo poblacional, como un sujeto diferenciado a ser incorporado en la gestión del riesgo y se precisa que se entiende por enfoque diferencial. 

Las categorías campesino y ruralidad han tenido distintas connotaciones como categorías mediadoras del relacionamiento del Estado con un determinado grupo de la población rural [29]. El término campesino ha servido en doble vía como objeto de norma, regulación y mecanismo de mediación estatal, como forma para nombrar a los sujetos de distintas demandas sociales en contextos históricos específicos [30]. 

El término campesino, además de ser un concepto retórico, es decir que hace parte de la construcción de un discurso, es también un concepto relacional, ya que lo constituyen las relaciones intersubjetivas, políticas y sociales. De manera que es pertinente reflexionar sobre las asociaciones que se hacen a la noción y a la multiplicidad de sus significados [30]. Esa multiplicidad de asociaciones y significados que se convocan por la expresión campesino, son cambiantes y dinámicos dependiendo de las ideas, formas sociales y culturales con que se relacionan y al contexto histórico y espacial. 

Un recorrido por las principales teorías que se ocupan de la categoría social-campesino y su papel en la sociedad desde el marxismo, a la teoría chayanoviana, se hace un llamado a que los estudios sobre el campesinado se abran a nuevas formas de pensamiento [31]. Mostrando que la categoría campesino, como no encaja en las lógicas del capitalismo ha sido invisibilizada o se le ha restado importancia. Tanto los estudios de la economía clásica, como los de economía marxista consideran la categoría social-campesinado como una categoría en proceso de extinción, anacrónica y que es un obstáculo para el desarrollo [31]; sin embargo, la categoría pervive: los campesinos son personas, comunidades y unidades de producción familiar en medio del auge del desarrollo capitalista. 

El campesino hoy se nombra como un sujeto global que lucha por su identidad, por visibilizarse y por diferenciarse cultural y socialmente frente a otros grupos. Las luchas campesinas actuales entran en diálogo con el discurso multiculturalista y con las experiencias de exclusión de las minorías étnicas. El campesino se auto-reconoce y se auto-identifica como un grupo poblacional y a su vez como un actor político.


::: {.caja-box}
**Caja 3.** Elementos para la conceptualización del campesino El Instituto Colombiano de Antropología e Historia (ICANH) elaboró un documento técnico con los elementos para la conceptualización de lo campesino dirigido a su inclusión como sujetos diferenciados en el Censo del DANE. Dichos elementos son [32]: Dimensión socio-territorial. - Relación estrecha con la tierra. - Formas de posesión de la tierra asociativas y vecinales. - Vinculación con la naturaleza. Dimensión socio-cultural. - Autoreconocimiento individual, familiar y comunitario como campesinos. - Formas de vida campesinas. Dimensión Político-productiva. - Trabajo con la tierra: recolectores, cultivadores, pescadores y criadores. - Productores de alimentos, de valores de uso y de materias primas. - Sujeto económicamente multiactivo. - Autoconsumo. Dimensión organizativo-política. - Sujeto participativo. - Autoafirmación como campesino.

:::

Es importante reiterar que la población campesina ha estado sumida en unas condiciones de pobreza, desigualdad social, abandono del Estado y de la sociedad, que han llevado a que en muchas ocasiones el concepto campesino se asocie con el concepto de pobreza; es decir, que campesino-pobreza se consideren como sinónimos o incluso que la pobreza se perciba como una característica identificadora del campesino [17,33,30]. 

La inexistencia de un concepto claro de campesino que defina a un sujeto social específico es una de las causas por las que el problema del campo y de los campesinos sigue sin resolver a pesar de las políticas estatales dirigidas a este sector [33]. 

La configuración de una identidad campesina, más allá de representar una forma de relacionamiento entre los campesinos y el Estado, implica la posibilidad de su reconocimiento como sujetos especiales de derecho. Al respecto, es menester mencionar que la constitución de 1991 no reconoce a los campesinos como un grupo culturalmente diferenciado y, por tanto, tampoco reconoce una condición de especial protección de sus derechos a diferencia de los indígenas y los afrocolombianos [34,30]. 

Frente a los campesinos, la Constitución Política se limita a identificar la problemática de los trabajadores agrarios para su acceso a la propiedad de la tierra (artículo 64 C.P), que se aborda desde el derecho agrario y las políticas públicas de desarrollo rural basadas en el aumento de la productividad. En contraste, no hay una garantía específica dirigida a proteger el derecho de los campesinos a tener una vida digna, o de sus derechos económicos, sociales, culturales y ambientales (verbigracia el derecho a que se protejan sus semillas y conocimientos tradicionales), ni de sus derechos civiles y políticos (como podría ser por ejemplo, el derecho a la consulta previa establecido para comunidades étnicas). 


::: {.caja-box}
**Caja 4.** Derechos económicos, sociales y culturales Los derechos económicos, sociales y culturales pueden definirse como los derechos que nacen de la dignidad humana y son, por ende, inherentes a la persona humana. Por tanto, son derechos directamente relacionados con la protección de las necesidades y capacidades que garantizan una calidad de vida [35]. En la Constitución de 1991 se consagran principalmente en el Capítulo 2 del Título II, artículos 42 a 77.

:::

A diferencia de los grupos étnicos, los sectores campesinos mestizos tienen que apelar a su inclusión en las lista de desplazados o su vinculación como guardabosques para acceder a los beneficios de las políticas sociales focalizadas [36], así que en un contexto de desmantelamiento de la política agraria, de pobreza y desempleo rural, el ingreso a la categoría de población vulnerable frente a la violencia es una nueva estrategia de rebusque económico y de inclusión política y social usada por los campesinos. Sin embargo, el uso de esta estrategia se puede objetar por cuanto está asociada a los fenómenos de violencia que ha sufrido el país, lo que se constituye en una forma de re-victimización [37]. Además, esta estrategia no reconoce la identidad campesina, dejando por fuera a quienes no pueden hacer uso de la misma, por no tratarse de víctimas directas de la violencia, es decir un buen número de ellos. Si bien, la categoría campesino se invisibiliza permanentemente en las políticas públicas, ésta sigue siendo vigente como categoría cultural y como un referente de autodefinición [38].

La idea de identidad como estrategia de relacionamiento con y frente al Estado a través del derecho, se constituye como un campo de lucha por el reconocimiento identitario como sujeto de derecho diferente a otros grupos que les permita acceder en condiciones de equidad a sus derechos. En otras palabras, el proceso de reivindicación político-jurídico de lo campesino, plantea que los derechos campesinos deben reconocerse explícitamente en la norma; sin embargo, en la práctica esto es difícil de conseguir, incluso para sujetos especiales con reconocimiento constitucional como tal desde 1991, como es el caso de los indígenas [38].

El desconocimiento de la condición de campesino tiene una importante incidencia para esta población en los procesos de gestión del riesgo de desastres, los cuales no desarrollan ninguno de sus procesos de manera diferenciada para esta población. Esto los deja en una situación de aumento de su vulnerabilidad en aspectos como la exposición de sus medios de vida, la ruptura de su especial forma de relacionamiento con el territorio y el desconocimiento de sus particularidades culturales. Por razones de espacio nos referimos únicamente al proceso del conocimiento del riesgo de desastres.

En el proceso del conocimiento del riesgo, que implica la recopilación y análisis de información específica para la población campesina, desde la identificación de la vulnerabilidad (física, social, económica y cultural), el nivel de exposición, las causas de los desastres, la forma en que los afectan y la magnitud de los impactos, es fundamental para garantizar los derechos de los campesinos, ya que permite que en los procesos de reducción del riesgo y manejo de desastres se tengan en consideración las particularidades de esta población. 

Un enfoque diferencial permitirá a la gestión del riesgo identificar las necesidades específicas de los campesinos, establecer su vulnerabilidad actuando sobre ella y tener en consideración las diferencias socio-económicas y culturales al momento de planear las intervenciones. Para ello, se propone entender el enfoque diferencial como un proceso político en el que se afirman derechos asociados a una identidad [27]; es decir, que reconoce “las diferencias físicas, sociales y culturales de cada grupo poblacional y de cada sujeto, individual y colectivo, de forma que sea posible reconocer su experiencia e historia particular que los identifica o representa” [37, p.29]. De igual manera permite adoptar orientaciones que indican acciones y caminos específicos a seguir en los distintos procesos de la gestión del riesgo frente a las poblaciones campesinas en Colombia para asegurar sus derechos humanos, en especial su derecho a una vida digna.



**Figura 2.** Proceso social de la gestión del riesgo de desastres. Elaboración propia con la APP Canva.

## CONCLUSIONES

La gestión del riesgo de desastres de origen natural y socio–natural debe entenderse como una política de desarrollo estrechamente vinculada con las políticas de protección social, que se constituye en un posibilitador de calidad de vida y bienestar para la población, por ende, para la concreción en la práctica del derecho a la vida digna. Sin embargo, para todos los grupos poblacionales, este derecho no se concreta de igual forma por lo que es necesario realizar acciones positivas frente a los grupos más vulnerables como los campesinos. Para ello se requiere inicialmente que la recolección de información se diferencie y que se realicen estudios que se enfoquen específicamente en este grupo poblacional. 

La tarea propuesta no es sencilla, ya que si bien frente a grupos positivamente diferenciados, como por ejemplo las comunidades étnicas o las mujeres, existen niveles de aprobación frente a quienes los integran y la necesidad de brindarles una especial protección desde el derecho. En el caso de los campesinos aún no existe consenso en su conceptualización como categoría, ni sobre quiénes son los sujetos individuales que forman este grupo social y menos sobre su consideración como grupo sujeto especial de derecho. Por lo anterior, es indispensable considerar la relación riesgo/desarrollo sostenible desde la implementación de la política de gestión del riesgo de desastres dirigida a los campesinos que dé respuesta anticipada a los impactos negativos que los desastres socio-naturales tienen sobre el bienestar de estas poblaciones, y cómo las políticas públicas de protección social pueden generar soluciones acordes a las características y condiciones propias de los campesinos. 

La política de gestión del riesgo de desastres con enfoque diferencial requiere incluir acciones de protección social, pero en una relación de doble entrada. Las políticas de protección social deben incorporar la gestión del riesgo de desastres, específicamente el conocimiento del riesgo y la reducción del riesgo. Esto se constituye en una estrategia que les permite obtener mejores resultados ambas políticas. 

Se propone una política de gestión del riesgo de desastres con enfoque diferencial para los campesinos que focalice la reducción de desastres teniendo como punto de partida la planificación y el ordenamiento del territorio más que el diseño y construcción de obras de mitigación, que priorice acciones de protección social como son empleo, subsidios o transferencias de efectivo y seguridad social direccionados a las comunidades campesinas. 

Para lograrlo se requiere aumentar considerablemente la información y las evaluaciones sobre el riesgo de desastres y considerando la desproporcionada afectación que los grupos de población más vulnerable sufren con los desastres, es importante que la información recogida facilite la identificación de los tipos de sujetos, por cuanto la recolección de información sin tener en cuenta indicadores que diferencien los grupos poblacionales (como por ejemplo mujeres, niños, indígenas o campesinos) encubre la gravedad de los impactos de los desastres para las poblaciones campesinas. 

La legitimación de la recolección de información diferenciada para las comunidades campesinas, se fundamenta en que contar con información específica posibilita desenmascarar las profundas desigualdades derivadas de la pobreza y la exclusión social. Si se asocian los efectos devastadores intrínsecos de los desastres socio-naturales a la existencia de una alta vulnerabilidad generada por la existencia de altos índices de pobreza, entonces se percibe claramente que la vulnerabilidad socioeconómica es clave en el entendimiento de las causas de los desastres, y cómo las consecuencias de estos no son homogéneas, sino que se distribuyen según las condiciones de dicha vulnerabilidad. 

Asimismo, si se logra que las medidas adoptadas sean más acordes a las características, idiosincrasia y cultura de las comunidades y damnificados, y se incorporan medidas alternativas creadas por los saberes propios de las comunidades, en este caso comunidades campesinas, se garantiza un mayor nivel de éxito, el intento de homogeneización de los conceptos de reducción y adaptación, desarrollados sólo desde el lado técnico, no permite identificar los demás sistemas que responden a otras realidades, cosmovisiones, prácticas y ethos [38].

En igual medida, se considera importante señalar que el enfoque diferencial permite a la gestión del riesgo de desastres entender que los derechos humanos son una integralidad y que su concreción en la práctica contribuye a superar las condiciones de invisibilización de los campesinos partiendo del reconocimiento identitario de los campesinos, lo cual implica que la planificación del territorio y la gestión del riesgo de desastres se realice con la participación de los mismos, de forma que posibilite la protección de sus derechos, sobre todo, el derecho a disfrutar de una vida en condiciones óptimas y dignas. 

## MATERIALES Y MÉTODOS

El método implementado es cualitativo y el enfoque que orientó la investigación es el hermenéutico [39], que comprende tres pasos o momentos, el acercamiento interpretativo a los textos, el acercamiento a las comunidades campesinas en cuanto sujetos–objetos de investigación y la síntesis que conjuga la interpretación textual, con la interpretación que el investigador realiza de lo expresado por los sujetos. En este artículo se presentan los resultados del primer momento en el cual, en la búsqueda de una creación, de un aporte al saber jurídico, se desenvuelve una experiencia que es el momento del pensamiento, del cuestionamiento, de la reflexión sobre la pregunta de investigación que nos llevó a cuestionarnos sobre las propuestas que desde el derecho, contribuyen al mejoramiento de la calidad de vida de las poblaciones, para el caso de estudio indagar sobre cómo desde la gestión del riesgo de desastres socio-naturales se puede posibilitar el derecho a la vida digna de los campesinos en Colombia. 

La pregunta de investigación, como proyecto de sentido, posibilita por medio del proceso interpretativo conversar con los textos -literatura especializada, jurisprudencia de la Corte Constitucional y normatividad. Las técnicas e instrumentos utilizados fueron los reseñados en la **Tabla 1**.

**Tabla 1:** Técnicas e instrumentos para la recolección de la información. Elaboración propia.


| Técnicas e instrumentos para la recolección de la información | Técnicas e instrumentos para la recolección de la información | Técnicas e instrumentos para la recolección de la información |
| --- | --- | --- |
| Técnicas | Instrumentos | Fuentes |
| Revisión bibliográfica | - Fichas de resumen | Bibliografía especializada nacional e internacional |
| Revisión jurisprudencial. | - Fichas de análisis - Fichas textuales | Jurisprudencia Corte Constitucional 1992-2021. |
| Revisión normativa | - Fichas de análisis  - Fichas textuales | CONPES, Política Nacional y Legislación en materia de propiedad rural, ordenamiento territorial, gestión del riesgo de desastres y desarrollo rural. |
| Revisión de datos. | -Fichas estadísticas | Encuesta Nacional de Calidad de Vida (ECV) 2019. Censo Nacional de Población y Vivienda 2018. Encuesta Nacional Agropecuaria 2010, 2014. Censo Nacional Agropecuario 2014. Datos del Departamento Administrativo de Planeación Nacional.  Datos de la Unidad Nacional de Gestión del Riesgo de Desastres (UNGRD). Datos del Sistema de Alertas Tempranas del Valle de Aburrá (SIATA). Datos de la Unidad de Planificación Rural Agropecuaria (UPRA). |


| PUNTOS CLAVE La gestión del riesgo de desastres debe considerarse como una política pública de protección social y por tanto incorporar aspectos como generación de empleo, subsidios o transferencias de efectivo y seguridad social, como mecanismos adicionales para la gestión del riesgo de desastres direccionados a las comunidades campesinas. El campesino es un sujeto histórico que se ha configurado según cada época pero que siempre se ha auto reconocido como campesino. Es necesario realizar una gestión del riesgo de desastres con enfoque diferencial, de forma que se identifiquen los distintos sujetos de la misma y sus intersecciones. |
| --- |


| NECESIDADES FUTURAS Y RECOMENDACIONES Es necesario que la gestión del riesgo en Colombia incorpore un enfoque diferencial para las comunidades campesinas, con el objetivo de cumplir con el mandato constitucional del artículo 7, en virtud del cual se reconoce y protege la diversidad étnica y cultural. El primer paso a dar es la recolección de información discriminada para este grupo poblacional, que reflejé como los desastres los afectan realmente. En un segundo momento, es necesario revisar si los datos recopilados de forma discriminada frente a diferentes grupos poblacionales, inciden o no en la adopción de medidas igualmente diferenciadas. |
| --- |

## CONFLICTO DE INTERESES

Las autoras no declaran conflicto de intereses 

**CONTRIBUCIÓN DE AUTORÍA CRediT**

Conceptualización: SEAV, SPDQ. Metodología: SEAV, SPDQ. Redacción de primera versión: SEAV, SPDQ. Escritura. Revisión y edición de segunda versión: SEAV, SPDQ. Figuras y tablas: SEAV, SPDQ. Administración de proyecto: SEAV, SPDQ. Búsqueda de evidencia: SEAV.

## IDENTIFICACIÓN DE AUTORES

Sandra Eliana Alzate Vargas 

Sandra Patricia Duque Quintero 

## BIBLIOGRAFÍA

DANE (Departamento Administrativo Nacional de Estadística). (2019). *Manual de Conceptos Censo Nacional de Población y Vivienda-Cnpv 2018.* 

2. 	DANE (Departamento Administrativo Nacional de Estadística). (2020). *Encuesta Nacional de Calidad de Vida ECV 2019*, *Resultados-Identificación Subjetiva De La Población Campesina*. 

3. 	Departamento Administrativo Nacional de Estadística - DANE. (2021). *Metodología General Encuesta Nacional de Calidad de Vida.* 

4. 	Mantilla García, J.C. (2016). *Vida digna: Hacia un horizonte normativo para el Desarrollo Humano en la Colombia Rural*. [Tesis de doctorado, Pontificia Universidad Javeriana] 

5. 	MADS (Ministerio de Ambiente y Desarrollo Sostenible), PNUD (Programa de las Naciones Unidas para el Desarrollo), Bárcenas Sandoval J, Gómez Castiblanco L, Wilchex-Chaux, G. (2016), *Curso en Gestión del Riesgo de Desastres para Autoridades Ambientales en Colombia. Unidad I: Marco conceptual, institucional y normativo.* 

6. 	MADS (Ministerio de Ambiente y Desarrollo Sostenible), PNUD (Programa de las Naciones Unidas para el Desarrollo), Carrión Barrero, GA. (2016). *Curso en Gestión del Riesgo de Desastres para Autoridades Ambientales en Colombia. Unidad II: Gestión de riesgos de desastre en la planificación territorial.* 

7. 	Oficina de las Naciones Unidas para la Reducción del Riesgo de Desastres -UNDRR. (2021, 3 de agosto). *DesInventar Sendai*. 

8.	UNGRD (Unidad Nacional para la Gestión del Riesgo de Desastres). (2022, 8 de abril). *Monitoreo de Amenazas Naturales - 8 de abril de 2022.* .

9.	UNGRD (Unidad Nacional para la Gestión del Riesgo de Desastres), Cardona Arboleda, O., Bernal, G., Marulanda Fraume, P., Villegas, C., González, D.; Escovar, M. A., Carreño, M., Marulanda Fraume, M., (2019) *Atlas de Riesgo de Colombia: Revelando los Desastres Latentes.* 

10. 	Cardona Arboleda, O. (2001). *Estimación Holística del Riesgo Sísmico Utilizando Sistemas Dinámicos Complejos*. 

11. 	Blaikie, P., Terry, C., Davis, I., Wisner, B. (1994). *At risk. Natural Hazards, People´s Vulnerability, and Disasters*. Taylor & Francis e-Library. https://doi.org/10.4324/9780203714775

12. 	Turner, B., Kasperson, R., Matson, P., Matsone, P., McCarthy, JJ., Corell, RW., et al. (2003). A framework for vulnerability analysis in sustainability science. *Proceedings of the National Academy of Sciences, 100*(14), 8074–9. 

13. 	Wilches-Chaux, G. (2017). Vulnerabilidad Global. *Journal of Chemical Information and Modeling, 8*(9),1–58. 

14. 	Soares, D., Murillo-Licea, D. (2013). Percepciones Sociales y Cambio Climático. *Cuadernos de Desarrollo Rural, 10*(72),181–199. 

15. 	De la Fuente, A. (2010). Desastres Naturales y Pobreza En América Latina: Impacto Al Bienestar y Soluciones de Protección Social. *Bienestar y Política Social,* 6(1),1–16. 

16. 	Lampis, A. (2010). *Pobreza y Riesgo Medioambiental: Un problema de Vulnerabilidad y Desarrollo*. 

17. 	PNUD (Programa de las Naciones Unidas para el Desarrollo). (2011). El Campesinado Reconocimiento para construir País*. Cuaderno del Informe de Desarrollo Humano, Colombia.* 

18. 	Mosquera Téllez, J., Gómez Carvajal, ER. (2012). Bases Conceptuales para la Gestión Integral del Riesgo. *Luna Azul,* (34):148–69. 

19. 	Villareal Camacho, KA. (2016). Aporte de la Política de Gestión del Riesgo de Desastres a la Reducción de la Pobreza en Colombia desde un Enfoque de Vulnerabilidad Social. 

20. 	Campos-Vargas, M., Toscana-Aparicio, A., Campos Alanís, J. (2015). Riesgos Socionaturales: Vulnerabilidad Socioeconómica, Justicia Ambiental y Justicia Espacial. *Cuadernos de Geografía. Revista Colombiana de Geografía, 24*(2):53–69. 

21. 	Mora, M., Saffon, M. P., Gómez, P. (2018). Investigación-Acción Durante Desastres: Uso de Redes y Derechos. *Revista Mexicana de Sociología,* (80), 95–119. 

22. 	Acuña Gamba, E. J., (2016). Responsabilidad Del Estado Por Fallas Geológicas. *Revista Vía Iuris*, *21*(8), 47–67.

23. 	Kasperson, RE., Renn, O., Slovic, P., Brown, HS., Emel. J., Goble, R., et al. (1988). The Social Amplification of Risk: A Conceptual Framework. *Risk Analysis,* *8*(2):177–87. 

24. 	Unidad Nacional de Gestión del Riesgo de Desastres - UNGRD, Comité Nacional para el Conocimiento del Riesgo - SNGRD. (2017). Terminología sobre Gestión del Riesgo de Desastres y Fenómenos Amenazantes. 

25. 	Pérez Aldana, LY. (2016). El desarrollo como Determinante de la Magnitud de los Desastres en Colombia 2000-2012. 

26. 	Oficina de las Naciones Unidas para la Reducción del Riesgo de Desastres -UNDRR. (2019). *Informe de Evaluación Global sobre la Reducción del Riesgo de Desastres (síntesis). Hacia el Desarrollo Sostenible*. 

27. 	Olivar Rojas, AF. (2020). Políticas Públicas y Enfoques Diferenciales: Aproximaciones desde la Interculturalidad y la Democracia Radical. *Iztapalapa Revista Ciencias Sociales y Humanidades, 88*(1). 

28. 	Lampis, A. (2019). ¿Qué Ha Pasado con la Vulnerabilidad Social en Colombia? Conectar Libertades Instrumentales y Fundamentales. *Sociedad y Economía*. (19), 229-261. 

29. 	Yie Garzón, SM. (2018) *¡Vea, Los Campesinos Aquí Estamos!: Etnografía De La (Re)Aparición Del Campesinado Como Sujeto Político En Los Andes Nariñenses Colombianos*. [Tesis doctoral, Universidade Estadual de Campinas. Instituto de Filosofia e Ciências Humanas]. 

30. 	Velasco Olarte, ME. (2021, 2 de agosto). *Quienes Son Hoy los/as Campesinos/as: Un Acercamiento al Proceso de Construcción de Identidad Campesina en el Marco del Conflicto Armado en Colombia. Caso de Estudio: Las Zonas de Reserva Campesina*. .

31. 	Mora Delgado, J. (2008). Persistencia, Conocimiento Local y Estrategias de Vida en Sociedades Campesinas. *Revista de Estudios Sociales,* (29),122–33. 

32. 	Instituto Colombiano de Antropología e Historia -ICANH. (2017, febrero). *Elementos para la conceptualización de lo “campesino” en Colombia Documento técnico elaborado por el ICANH*. 

33. 	Salgado Araméndez, C. Los Campesinos Imaginados. (2002). *Cuadernos Tierra y Justicia. ILSA,* (6):40. 

34. 	Chacón Hernández, D. (2018). ¿Y qué hay de los derechos humanos campesinos? *Alegatos - Revista Jurídica de la Universidad Autónoma Metropolitana*, *18*(1):815–41. 

35. 	Duque Quintero, SP., Duque Quintero, M., González Sánchez, P. (2019). Sobre el Derecho Fundamental Al Mínimo Vital o a La Subsistencia: Análisis Jurisprudencial. *Revista Encuentros, 17*(01):80–95. 

36. 	Rodríguez, JN., Camacho, SJ. (2013). ¿Quiénes son los campesinos colombianos hoy? *Universidad, Ciencia y Desarrollo*. 

37. 	Arteaga Morales, BI. (2012). El Enfoque Diferencial: ¿Una Apuesta Para La Construcción De Paz? [Internet]. En: Observatorio de Construcción De Paz. (Eds.), *Identidades, Enfoque Diferencial y Construcción de Paz. Serie Documentos Para La Paz (N° 3*., p.p.15–38). Universidad Jorge Tadeo Lozano. 

38.	Salinas, V., Cevallos, W., Levy, K. (2020). Afrodescendientes e Indígenas Vulnerables Al Cambio Climático: Desacuerdos Frente A Medidas Preventivas Estatales Ecuatorianas. *Iconos,* *24*(66),107–29. 

39. 	González Agudelo, E. (2011). Sobre La Experiencia Hermenéutica o Acerca de Otra Posibilidad Para La Construcción Del Conocimiento. *Discusiones Filosóficas*, *12*(18),125–43. 

