---
title: "Capítulo 14: Gestión del riesgo en salud en situación de desastres. Lecciones aprendidas en Armenia"
author:
  - "Olga Alicia Nieto Cárdenas"
title-block-banner: "images/banner_2023.png"
---

1Programa de Medicina. Facultad de Ciencias de la Salud. Universidad del Quindío. Carrera 15 calle 12 Norte. Armenia, Quindío, Colombia. Correo-e: oanieto@uniquindio.edu.co

## Resumen {.unnumbered}

El 25 de enero de 1999 ocurrió un terremoto de magnitud 6.2 que generó un desastre en el Quindío y eje cafetero que afectó el Municipio de Armenia Quindío, con gran mortalidad y daños en la salud y la infraestructura. En este capítulo se resume cómo fue el manejo de la salud pública durante este desastre. Se encontró que la Secretaría de Salud del Municipio de Armenia tenía un plan orientado hacia las cinco áreas de la promoción de la salud, reorientar los servicios de salud, desarrollar ambientes saludables, propiciar estilos de vida saludables, propiciar la participación social y políticas públicas saludables. Para enfrentar la situación generada por el terremoto la Secretaría adoptó el modelo de Atención Primaria en Salud al cual denominó Gestión del Riesgo con los componentes de atención a las personas, atención al ambiente, vigilancia en salud pública y educación básica en situación de desastre en el contexto de ciudad educadora definida por el municipio. El municipio de Armenia y la Secretaría de Salud habían enfrentado el año anterior (1998) una epidemia de dengue y tenían una línea base de información y un equipo de salud pública. Durante el desastre, las diferentes instituciones atendieron a las víctimas apoyados por la Red Nacional de Urgencias Emergencias y Desastres, se atendieron unas 6,500 personas en urgencias y rescataron 1,109 cadáveres, el 83% de Armenia. El proceso de reconstrucción estuvo liderado desde el Gobierno Nacional por el FOREC (Fondo para la reconstrucción del eje cafetero) y hubo ONG ejecutoras en 15 gerencias zonales en el municipio de Armenia. Se concluye que el municipio de Armenia tenía un plan enfocado hacia la promoción de la salud y asumió el concepto de gestión de riesgo en salud durante el manejo del desastre. Se recomienda fortalecer los planes de gestión del riesgo de desastres.

**Palabras clave**: desastres, efecto de desastres en la salud, gestión del riesgo, salud pública

**Health risk management in disaster situations. Lessons learned in Armenia**

## Abstract {.unnumbered}

On January 25, 1999, an earthquake of magnitude 6.2 occurred that generated a disaster in Quindío and the coffee region that affected the Municipality of Armenia Quindío, with significant mortality and damage to health and infrastructure. This chapter summarizes the management of public health during this disaster. It was found that the Secretary of Health of the Municipality of Armenia had a plan oriented toward the five areas of health promotion, reorienting health services, developing healthy environments, promoting healthy lifestyles, promoting social participation, and healthy public policies. To face the situation generated by the earthquake, the Secretary adopted the Primary Health Care model, which is called Risk Management with the components of care for people, care for the environment, public health surveillance, and primary education in disaster situations in the context of an educating city defined by the municipality. The municipality of Armenia and the health secretary had faced a dengue epidemic the previous year (1998) and had a baseline of information and a public health team. During the disaster, the different institutions attended to the victims supported by the National Network of Emergencies and Disasters, attended to some 6,500 people in the emergency room, and rescued 1,109 bodies, 83% from Armenia. The National Government led the reconstruction process by FOREC (Fund for the Reconstruction of the Coffee Axis), and there were executing NGOs in 15 zonal administrations in the municipality of Armenia. The conclusion is that the municipality of Armenia had a plan focused on health promotion and assumed the concept of health risk management during disaster management. The recommendation is to strengthen disaster risk management plans.

**Keywords**: Disasters, health effects of disasters, risk management, public health

## 1. MARCO CONCEPTUAL SOBRE LA GESTIÓN DEL RIESGO EN SALUD

## 1.1 La gestión del riesgo en salud, varias aproximaciones

**El riesgo en salud.** El interés por los riesgos en salud ha existido siempre pero cada vez más incluye nuevas perspectivas para el análisis de riesgos y tiene como punto de partida la definición, identificación, cuantificación y caracterización de amenazas para la salud humana y el medio ambiente. Desde esta perspectiva el concepto de riesgo puede denotar una adversidad o amenaza potencial, una consecuencia o un factor que puede aumentar el efecto adverso; en este sentido el concepto de riesgo en salud se ha transformado en distintos contextos, tales como [1]:

Prevalencia del riesgo o proporción de la población que está expuesta a un riesgo.

Riesgo relativo o la probabilidad de obtener un efecto adverso en personas expuestas en comparación con personas no expuestas.

Peligro o la propiedad inherente a una sustancia, cosa, suceso, que encierra un potencial de nocividad.

Riesgo atribuible poblacional o la proporción de una enfermedad existente en una población que puede atribuirse a un riesgo particular.

Carga atribuible o la proporción de la carga actual de morbilidad debida a una exposición anterior.

Carga evitable o la proporción de la carga futura de enfermedad que puede evitarse si se reducen los niveles de exposición [1].

A continuación, se precisa el concepto de riesgo desde la epidemiología, una ciencia que ha aportado notoriamente en esta construcción.

**El riesgo en epidemiología.** El concepto de riesgo en epidemiología equivale al efecto, probabilidad de ocurrencia de una patología en una población determinada y se expresa a través del indicador conocido como Incidencia. Este concepto reposa sobre tres supuestos epidemiológicos: la identidad entre lo posible y lo probable, el concepto de homogeneidad en la naturaleza de la morbilidad, y el supuesto de recurrencia de los eventos. Este último justifica la aplicación del concepto de riesgo en modelos de prevención, conociendo sus determinantes para intervenir en su proceso [2]. 

El concepto de riesgo relativo permite la construcción del concepto denominado *Factor de riesgo* y surge así una red de riesgos en la cual los comportamientos, señales, síntomas y enfermedades, pueden convertirse en factores de riesgo para otras afecciones. Por ejemplo, la hipertensión para la enfermedad cardiaca con lo cual surge un discurso biomédico, una condición medicalizable, el “estado de salud bajo riesgo” que permite una intervención [2].

Es decir, el riesgo es un concepto que requiere permanente actualización y el futuro del concepto depende de la capacidad de articularse con nuevos desarrollos conceptuales y metodológicos [2]. Desde la perspectiva epidemiológica del factor de riesgo que se puede identificar y permite una intervención se avanza hacia el concepto de gestión del riesgo. Según el Centro de Conocimiento en Salud Pública y Desastres [3] la gestión del riesgo en el sector salud sigue los siguientes pasos: El análisis de amenaza y vulnerabilidad, la reducción del riesgo y la evaluación del impacto potencial.

El concepto y la gestión del riesgo en el sistema general de seguridad social en Colombia. El concepto de riesgo entendido como la probabilidad que ocurra un efecto adverso que afecte nuestra salud y vida orienta la posibilidad de prevenir en salud y la idea de trabajar en la detección del riesgo como una opción de prevención en salud, es una constante en la historia de la salud pública. 

Es así como el concepto de gestión de riesgo llega al Sistema General de Seguridad en Salud en Colombia (SGSSS) y empieza a permear distintos ámbitos tales como la gestión del riesgo colectivo, la gestión del riesgo en los aseguradores de salud y más recientemente la gestión del riesgo en las rutas de atención integral en salud (RIAS). 

En el desarrollo del SGSSS en Colombia se precisa la importancia de los conceptos de detección temprana del riesgo e inducción a la demanda [4] y posteriormente se llega al concepto de gestión del riesgo. El Plan Decenal de Salud Pública 2012-2021 (PDSP) concibe el riesgo en salud como “la probabilidad de ocurrencia de un evento no deseado, evitable y negativo para la salud del individuo, que puede ser también el empeoramiento de una condición previa o la necesidad de requerir más consumo de bienes y servicios que hubiera podido evitarse” [5,6].

En el aseguramiento en salud se define el sistema de administración de riesgos y el riesgo desde la perspectiva epidemiológica se relaciona con el riesgo desde la perspectiva empresarial, como la probabilidad de generación de pérdidas económicas por la ocurrencia de un evento adverso derivado de las actividades propias del negocio [7].

Más recientemente el SGSSS llega al concepto de rutas integrales de atención en salud con el objetivo de integrar a todos los actores del sistema para una adecuada gestión del riesgo en salud [8], en desarrollo de la Política de Atención Integral en Salud (PAIS) y de modelos de atención integral (MIAS) [9,10].

### Marco conceptual sobre la gestión del riesgo en salud en situación de desastres

Según la Ley 1523 de 2012 la Gestión del Riesgo de Desastre “es un proceso social orientado a la formulación, ejecución, seguimiento y evaluación de políticas, estrategias, planes, programas e instrumentos, medidas y acciones para el conocimiento y reducción del riesgo y para el manejo de desastres con el propósito explícito de contribuir a la seguridad y el bienestar de las personas, la calidad de vida y al desarrollo sostenible” [11].  La Ley 1523 de 2012 generó un marco conceptual y normativo que ha permitido el desarrollo de una política de Gestión del Riesgo de Desastres en Colombia, en la cual todos los actores son partícipes y juegan roles complementarios en diferentes momentos, situación especialmente relevante para el sector salud.

### El marco normativo

**El marco normativo vigente en Colombia.** Al mirar retrospectivamente se puede pensar que Ley 1523 de 2012 es el único marco normativo en Colombia sobre este tema; sin embargo, la gestión del riesgo en el sector Salud tiene unas especificidades importantes a partir de la Constitución Política de 1991 [12], como puede verse en la Caja 1 [13].


::: {.caja-box}
**Caja 1.** Evolución del marco normativo en Gestión del Riesgo en Salud [13]. Todos estos desarrollos relacionados con la gestión del riesgo convergen actualmente al interior del Sistema General de Seguridad Social en Salud y de las entidades públicas y privadas que lo conforman. Sistema General de Seguridad Social en Salud, Decretos 1485 de 1994 y 723 de 1997. Acuerdo 117 de 1998 y las Resoluciones 412 y 3384 de 2000.  En el tema de riesgos profesionales se adoptó el Decreto 1295 de 1994. Decreto 1537 de 2001, sobre la organización y administración del sistema general de riesgos profesionales. Ley 46 de 1998, Sistema Nacional de Prevención y Atención de Desastres. Decreto 093 de 1998, el Plan Nacional para la Prevención y Atención de Desastres. Decreto 4110 del Icontec, adopta para Colombia la norma técnica dar AS/NZ 4360:1999 como pauta internacional de gestión del riesgo en salud.  Decreto 1599 del 2005, el Modelo Estándar de Control Interno, impacta la cultura organizacional de las entidades públicas del nivel nacional y territorial. Decretos 574 y 1698 de 2007 y la Resolución 1740 de 2008 que plantean la gestión del riesgo en salud en el marco de la habilitación financiera de las EPS. La Ley 1122 de 2007, adopta la gestión del riesgo en salud como función indelegable del aseguramiento en Salud. Decreto 3039 de 2007, define la prevención de riesgos como una de las cinco líneas de política del Plan Nacional de Salud Pública 2007–2010. La NTC ISO 31000 del 2011 contiene principios, marco de referencia y proceso de gestión del riesgo traducidos de la norma ISO 31000:2009. El Plan Decenal de Salud Pública 2012–2021, incluye una línea operativa que aporta elementos para el desarrollo de la gestión del riesgo en salud.

:::

**El marco internacional.** Desarrollos internacionales posteriores a la Ley 1523 hacen aportes significativos al desarrollo conceptual y operativo de la gestión del riesgo de desastres algunos de los cuales se mencionan en la **Caja 2**.


::: {.caja-box}
**Caja 2.** Aportes del marco internacional Los objetivos de desarrollo sostenible, la conferencia de las Naciones Unidas sobre vivienda y desarrollo urbano sostenible Hábitat III, el Acuerdo internacional de París COP21 y la convención marco de las Naciones Unidas sobre el cambio climático, el plan estratégico para la reducción del riesgo de desastres 2013–2018 de la Organización Panamericana de la Salud y la Organización Mundial de la Salud (OPS-OMS), el protocolo de Sendai y más recientemente el Informe RAR 2015–2030.

:::

El marco de Sendai para la Reducción del Riesgo de Desastres 2015–2030 retoma el concepto de resiliencia como la capacidad y necesidad de adaptarse y gestionar el riesgo en situaciones de desastre y propone cuatro prioridades de acción: comprender el riesgo de desastres, fortalecer la gobernanza, invertir en la reducción del riesgo de desastres para la resiliencia, y aumentar la preparación a fin de dar una respuesta eficaz [14].

### Las prioridades en salud pública en situación de desastre

Según Noji [16], los desastres se pueden considerar un problema de salud pública por varias razones (ver **Caja 3**). El concepto de gestión de riesgo en situación de desastre puede parecer en principio contradictorio porque frente a una situación de una magnitud tal que supera los mecanismos de prevención y control, lo primero que se hace es atender la fase de emergencia: rescatar a los lesionados, atender a los heridos, recoger los cadáveres. 


::: {.caja-box}
**Caja 3.** Los desastres son un problema de salud pública porque:  Pueden causar un número inesperado de muertes, lesiones o enfermedades, en la comunidad afectada que exceden las capacidades de los servicios locales de salud y requerir ayuda externa. Pueden destruir infraestructura local de salud lo cual limita la capacidad de respuesta ante la emergencia. Pueden tener efectos adversos sobre el medio ambiente y la población al aumentar el riesgo potencial de enfermedades transmisibles. Pueden afectar el comportamiento psicológico y social de las personas y las comunidades afectadas. Pueden generar escasez de alimentos lo cual trae consecuencias nutricionales.  Pueden generar grandes movimientos de población.

:::

Sin embargo, es necesario que tempranamente se identifiquen y controlen las amenazas y se atienda la vulnerabilidad, justamente para prevenir un desastre mayor. Es decir, la gestión del riesgo cotidiano es la clave en la atención misma del desastre, en todas sus fases, desde la fase de emergencia, hasta el análisis y evaluación del riesgo.

Las prioridades en salud pública en situación de desastres tienen que ver con agua potable, disposición de excretas, manejo de alimentos, control de vectores y zoonosis, control de enfermedades transmisibles y salud mental entre otros, las cuales se revisarán a continuación.

**Agua potable**. Según la OPS/OMS en una situación de emergencia son muchas las carencias, pero ninguna es tan importante como la necesidad de agua segura y en condiciones básicas de saneamiento, pues la falta de condiciones sanitarias después del desastre a menudo acarrea consecuencias sumamente graves para la población y causa aún más sufrimiento que el propio siniestro. Por lo tanto, agua y saneamiento deben figurar entre las prioridades de las autoridades locales y cuanto más rápidas y efectivas las medidas, menor será el daño [17]. 

El agua es uno de los principales medios de transmisión de enfermedades y por consiguiente al proveer la cantidad adecuada de agua a las poblaciones afectadas, las autoridades deben asegurar su potabilidad [18]. 

**Manejo de alimentos.** Después del agua son los alimentos los mejores vehículos para transportar gérmenes que puedan generar infecciones, especialmente en una situación de desastre, lo cual aumenta el riesgo de las enfermedades transmitidas por alimentos (ETA), que se producen por consumo de alimentos o agua  contaminados con bacterias, virus, hongos, parásitos o sustancias químicas que afectan la salud; las más frecuentes en situaciones de emergencia son: Hepatitis A, cólera, fiebre tifoidea y paratifoidea, cuyos síntomas más comunes son vómito, diarrea, fiebre, dolor de estómago o de cabeza y deshidratación, entre otros [18].

**Manejo de residuos.** Según el Ministerio de Salud en condiciones de emergencia el sitio de almacenamiento de residuos debe estar debidamente señalizado, distante de dormitorios, cocinas y alacenas. Debe mostrar con claridad las rutas y horas de recolección y contar con personas responsables del manejo de residuos sólidos. Debe permitir las actividades de aseo, desinfección y la recolección; debe disponer de recipientes impermeables de un tamaño que permita almacenar varias bolsas, y tener tapa que impida la entrada de agua, insectos o roedores [18]. Para la disposición final de residuos, cuando no haya un sistema de recolección y disposición por parte de las autoridades sanitarias, se sugiere que se adopte el método de trinchera [16,18]. 

**Disposición de excretas humanas.** El manejo inapropiado de los desechos humanos, aun en períodos sin desastres, afecta la salud pública [16]. Las enfermedades que se pueden transmitir a través del contacto con excrementos humanos incluyen la fiebre tifoidea, el cólera, la disentería, la hepatitis, la poliomielitis, la esquistosomiasis y la gastroenteritis, entre otras [18].

**Control de zoonosis y enfermedades transmitidas por vectores.** Los desastres agravan o generan condiciones que facilitan el criadero de los agentes que transmiten enfermedades, los cuales se conocen como vectores. Una zoonosis es una enfermedad que puede transmitirse de los animales a los seres humanos; existen muchos tipos de zoonosis y en situación de desastre hay que identificar su riesgo y reportar a la secretaría de salud en los siguientes casos: mordedura de animales como perros y gatos pueden transmitir rabia, mordedura de ratas y murciélagos pueden transmitir rabia silvestre; contacto con roedores o sus excrementos, puede transmitir leptospirosis; contacto con animales domésticos y silvestres expone al riesgo de pulgas, piojos, ácaros y al contagio de la fiebre por garrapatas [18].

**Albergues y alojamientos temporales.** Por lo general los asentamientos temporales son áreas con una densidad de población sumamente alta y se ubican en lugares que originalmente no estaban destinados a alojar tantas personas. Es probable que no existan servicios apropiados de salvamento y la falta de agua y de servicios higiénicos básicos puede aumentar el riesgo de enfermedades transmisibles, principalmente las endémicas en las áreas de origen, tránsito y asentamiento [16,17].

**La salud mental en situación de desastre**. Según la Organización Panamericana de Salud en situaciones de desastres y emergencias complejas se produce un deterioro del tejido social, una pérdida de la estructura de la vida familiar y un incremento de los signos de sufrimiento psicológico, como la aflicción y el miedo, que pueden aumentar la morbilidad psiquiátrica y otros problemas sociales. Según sea la magnitud del evento y demás factores, se estima que entre la tercera parte y la mitad de la población expuesta sufre alguna manifestación psicológica; aunque no todas pueden calificarse como patológicas, la mayoría deben entenderse como reacciones normales ante situaciones de gran significación o impacto. Después de una emergencia o desastre, los problemas de salud mental en los sobrevivientes requieren atención durante un periodo prolongado en el que tienen que enfrentar la tarea de reconstruir sus vidas [19,20].

Los principios para la atención de las personas con condiciones mentales, neurológicas y por uso de sustancias son comunicación, evaluación clínica, manejo y gestión, reducción de estrés y fortalecimiento del apoyo social, protección de los derechos humanos y atención al bienestar general [21].

## 2.	EL MANEJO EN SALUD PÚBLICA EN ARMENIA DURANTE EL TERREMOTO DE 1999

A continuación, se describe la situación y manejo de salud pública durante el terremoto del eje cafetero en el año 1999 con base en tres informes de la Secretaría de Salud del Municipio de Armenia: la atención de la emergencia durante el mes de enero, la estrategia de Atención Primaria en Salud en los seis primeros meses y el resumen de la gestión en el año 1999.



**Figura 1.** Fotografía de Armenia post terremoto en 1999 (izquierda) y en pandemia Covid 2021 (derecha). La figura muestra dos desastres diferentes, el posterremoto y la pandemia Covid. El impacto de los desastres del Siglo 21 afecta profundamente a los seres humanos, en su vida, salud y bienestar a pesar que la infraestructura física se conserve o mejore.

## 2.1 Perfil epidemiológico de la emergencia de enero de 1999

La Secretaría de Salud elaboró un informe sobre las personas atendidas el 25 y 26 de enero de 1999 según el cual se atendieron 6,407 personas, 42.8% hombres y 57.2% mujeres y el grupo etáreo más afectado fue 15–44 años. Se obtuvo información detallada de 4,667 afectados y se identificaron como causas de atención: otros traumatismos, otra herida en la cabeza, herida del codo, antebrazo y muñeca, contusión, fractura de húmero, herida de varios dedos de la mano, traumatismo intracraneal, herida de rodilla, pierna y tobillo y fractura de clavícula [22].

Se registraron 1,109 muertes, 921 en el municipio de Armenia (83%), 51.3% hombres y 48.7% mujeres, con predominio en el grupo 15–44 años y sus causas de muerte fueron: trauma craneoencefálico, politraumatismo, aplastamiento, sofocación, shock hipovolémico, trauma cerrado, insuficiencia respiratoria, shock traumático, anoxia e infarto agudo de miocardio [22].

El manejo de los cadáveres se llevó a cabo por el Cuerpo Técnico de la Fiscalía (CTI) en el coliseo de la Universidad del Quindío, donde se identificaban los cadáveres y se entregaban a los familiares.

La Secretaría de Salud manifestó que la principal causa de morbilidad y mortalidad fueron los traumas craneoencefálicos y politraumatismos, que afectaron principalmente a la población económicamente activa, lo que significa una importante pérdida en años de vida potencialmente perdidos (AVPP) y considera que se requiere mejorar la preparación institucional organizada para dar respuesta a ese tipo de traumas porque hace falta una red de urgencias en el municipio de Armenia como elemento integrador en el manejo de la fase post-desastre. La Secretaría contó con la red nacional de urgencias para el traslado y manejo de pacientes y se organizó una red de apoyo por parte de instituciones externas al municipio [22].

## 2.2 La estrategia de Atención Primaria en Salud (APS)

Según este informe con el fin de responder a las necesidades de la población damnificada en el municipio de Armenia ante el terremoto del 25 de enero de 1999, la Secretaría de Salud determinó la adopción de un modelo de Atención Primaria en Salud que se denominó Gestión del Riesgo, la cual tuvo los siguientes componentes: atención a las personas, atención al ambiente, vigilancia en salud pública y educación básica en situación de desastre en el contexto de ciudad educadora [23].

**Vigilancia en salud pública.** Se identificaron 25,649 personas de las cuales 24,135 se ubicaban en el área urbana y 1,434 en área rural. Se sectorizó la población a riesgo en 15 zonas con asignación de coordinadora y técnico en saneamiento para cada zona y también en los asentamientos espontáneos. A cada promotora de salud se le asignaron entre 100 a 150 familias con una programación de visita domiciliaria diaria promedio de 7–10 visitas y la organización de grupos homogéneos para el proceso educativo. La ubicación del personal se adaptó luego a la sectorización del municipio por gerencias zonales realizada por el Forec [23].

Se puso en marcha el sistema alerta-acción incluyendo enfermedades como la diarrea, la infección respiratoria aguda, la hepatitis A y la leptospirosis, lo cual permitió controlar los brotes de diarrea con una respuesta casi inmediata por los técnicos en saneamiento con el montaje de las pruebas en asociación con el Ministerio de Salud, el Instituto Nacional de Salud y el Instituto Seccional de salud del Quindío [23].

Se identificó la presencia del mosquito *Anopheles puntimacula* en varios sitios urbanos y rurales. Ante la presencia de personas procedentes de zonas endémicas se declaró la alerta amarilla y se capacitó a las promotoras para realizar búsqueda activa y toma de gota gruesa a las personas con fiebre procedentes de zonas maláricas [23]. El dengue había presentado una epidemia en el Municipio el año 1988 y estuvo controlado en el post-desastre (1999). Después del desastre aumentó la incidencia de diarrea, infección respiratoria, hepatitis A y varicela, sin presentar ninguna epidemia [23].

**Atención a las personas.** Se identificó la población a riesgo mediante un censo en los diferentes asentamientos y alojamientos, se priorizaron grupos vulnerables (niños, gestantes, ancianos, personas discapacitadas física o mentalmente) y se canalizó a las personas para la protección específica a la IPS según su seguridad social [23].  

En cuanto a la salud mental se diseñó un proyecto para la recuperación psicosocial para el personal de salud y la Alcaldía que estaba enfrentando la crisis emocional inmediata al terremoto, con una cobertura de 548 personas, con el apoyo de las ONG y universidades [23].

Con respecto a la participación comunitaria se identificaron los diferentes líderes en alojamientos y barrios para la conformación de los comités de salud y se impulsó su participación en el proceso de restauración del tejido social, primeros auxilios y deberes y derechos en las instituciones de salud [23]. 

**Atención primaria en salud ambiental.** La gestión cotidiana del riesgo en los asentamientos y alojamientos se enfocó en unas prioridades de salud pública que se describen a continuación. 

*Abastecimiento de agua*. Monitoreo de la calidad en la red, verificación diaria de la calidad en los asentamientos (pH, turbidez y coli fecal). Se hizo distribución de agua para los asentamientos sin conexión al acueducto con dos carrotanques aportados por el Ministerio de Salud [23].

*Higiene e inocuidad de alimentos*. Capacitación y desparasitación a manipuladores de alimentos de cocinas colectivas y comunitarias, monitoreo de ollas, cocinas y comederos colectivos y comunitarios, inspección de bodegas y centros de acopio [23].

*Saneamiento del medio*. Adecuación e instalación de unidades sanitarias en asentamientos temporales invasivos y permanentes, control, manejo y educación sanitaria para la disposición de excretas, educación e implementación para la correcta disposición de residuos sólidos [23].

*Higiene y seguridad en alojamientos*. Identificación del riesgo y orientación a la autogestión para prevención de accidentalidad; acciones de vigilancia y control de restaurantes, fábricas de alimentos, establecimientos comerciales, centros de acopio; control de vectores; monitoreo de recursos aire, agua, suelo y ambientes laborales. Esta labor fue efectuada por 22 técnicos en saneamiento y cinco auxiliares [23].

*Control de vectores*. Se hizo seguimiento de los índices aédicos, desinsectación química, fumigación peridomiciliaria, identificación y control de criaderos de anopheles con control biológico con bacilus thurigiensis [23].

*Control de zoonosis.* Se identificó aumento de las mascotas en los asentamientos y alojamientos, se hizo seguimiento a los accidentes rábicos en 24 barrios, 17 asentamientos y 4 alojamientos. Se hizo control de roedores atendiendo 2,092 viviendas con rodenticidas, pellets y cebos parafinados [23]. 

En informe remitido al Ministerio de Salud el 8 de junio de 1999 la Secretaría de Salud precisa que ha trabajado con la estrategia es la gestión cotidiana del riesgo; es decir; que identifico los riesgos tanto en atención a las personas, como en atención al ambiente, se analizó y se buscaron alternativas de solución diariamente. Sobre los asentamientos informa que existen 35 alojamientos temporales y persisten asentamientos espontáneos; existen también asentamientos invasivos que aparecieron al siguiente mes post terremoto por personas procedentes de fuera de Armenia como Urabá, Valle o Chocó. Estos sitios permanecían como de alto riesgo sanitario porque no era posible para el municipio instalar servicios de agua potable y saneamiento básico, lo cual estaría avalando la invasión de esos lotes. La Secretaría de salud facilitó la instalación de baños portátiles (al principio) y luego coordinó con algunas ONG la instalación de agua y baños en los límites de los asentamientos, pero persistía el problema de aguas servidas [23].

## 2.3 Informe de gestión y resultados 1999

Según el informe de gestión y resultados de la Secretaría de Salud de Armenia durante el año 1999 se llevó a cabo el Plan Local de Salud “Armenia Municipio Saludable por la Paz” cuyas cinco áreas se ajustaron en el contexto post-desastre como se describe en cada una de ellas [24].

**Reorientar los servicios de salud.** Se realizó vigilancia permanente en salud pública con funcionamiento del sistema alerta-acción, lo cual permitió hacer seguimiento a eventos y tendencias en morbilidad y factores de riesgo. Se realizó el diagnóstico de asentamientos temporales identificando grupos prioritarios tales como embarazadas, menores de 5 años y personas de la tercera edad, iniciando con ellos complementación nutricional.

El sistema general de seguridad social en salud avanzó en el aseguramiento y aumentó de 31,188 a 8,1188 afiliados al régimen subsidiado, pasando de 11% a 37% de la población afiliada. Esos 50,000 cupos fueron financiados por el Fondo para la Reconstrucción del Eje Cafetero (Forec) por 2 años y se asignaron recursos por más de $10,435 millones de pesos para cubrir a estos afiliados con la participación de 10 administradoras del régimen subsidiado. 

El desarrollo de la red de servicios avanzó en la articulación entre la red pública y privada con base en un análisis de mercado que facilitó la firma de convenios con las Empresas Sociales del Estado (ESE) del primer y tercer nivel de atención.  

Se gestionaron los recursos para la reconstrucción de la Red pública de atención con el Ministerio de Salud, que financió los centros de salud Nueva Libertad y Piloto. El Forec financió la relocalización de la Unidad Intermedia del Sur y de los centros de salud Santander, Correa Grillo, La Milagrosa y La Clarita, la reconstrucción del centro de salud El Paraiso y el reforzamiento de Miraflores, Los Quindos, El Caimo y La Patria. Se asignaron recursos por 7,935 millones para la relocalización y reconstrucción [24].

**Desarrollar ambientes saludables.** El desarrollo de ambientes favorables se enfocó en unas prioridades que se describen a continuación.

*Agua potable y saneamiento básico*. Se aplicaron 43 toneladas de cal para neutralización de ácidos orgánicos sobre los escombros y para el manejo de excretas en zanjas y trincheras, durante las primeras semanas post desastre.

En los asentamientos temporales se registraron inicialmente 20,362 habitantes y a diciembre de 1999 esta población se redujo en 48%, quedando 13,704 personas. El 92% tenían abastecimiento de agua potable, el 65% tenían conexión a la red de alcantarillado y el 79% tenían recolección de aguas inadecuada con zanjas. El 100% de los alojamientos recogían los residuos sólidos en bolsas plásticas, existían 14 contenedores para la recolección de residuos 7 botaderos a cielo abierto, la recolección se hacía 3 veces por semana. 

Se realizaron acciones permanentes en 49 asentamientos y 45 alojamientos temporales. El 100% de los alojamientos temporales tenían abastecimiento de agua potable por la Empresa de servicios Públicos de Armenia (EPA), 58% tanques de almacenamiento y dos se abastecían de pozos profundos (Cenexpo y talleres del Departamento). El 100% de los alojamientos tenía adecuada recolección de vertimientos líquidos hacia la red de alcantarillado. 

Se instalaron 507 baterías sanitarias con el apoyo de Unicef, Oxfam y Fundaps-Memisa y se redujo la presencia de baños individuales, en diciembre de 1999 persistían 51 letrinas húmedas y 19 baños móviles [24].

*Vigilancia y control de alimentos*. Se atendieron 1,879 establecimientos públicos dedicados al expendio de alimentos; es decir, el 32% de los 5,888 establecimientos que se identificaron post-desastre. Se hizo control de carne, leche y panela, al igual que de los vehículos transportadores de alimentos. 

*Control de vectores y zoonosis*. El dengue había presentado una epidemia en el Municipio de Armenia el año anterior (1998) y se mantuvo bajo control en el año 1999; se atendieron 48,727 viviendas en 257 sectores razón por la cual disminuyó la presencia de criaderos de larvas en los tanques de agua y se disminuyó el índice aédico promedio de 11.3 en 1998 a 8.8 en 1999 y en algunos barrios los índices aédicos bajaron a cero. 

*Control de la malaria*. Se identificaron 31 criaderos de anopheles (*puntimácula* y *argyritarsis*) en área urbana y rural y se encontraron 28 casos, uno autóctono.

*Control de zoonosis*. Se vacunaron 11,478 caninos y felinos en 80 barrios, 50 asentamientos y 45 alojamientos temporales. En los alojamientos y asentamientos se calculó la presencia de un perro por cada cuatro personas, lo cual aumentó el riesgo de accidentes rábicos que llegaron a ser 357. Se hizo control de roedores plaga en 244 sectores.

*Salud ocupacional*. Se visitaron 395 establecimientos públicos para identificar los riesgos y la accidentalidad laboral con la información de seis administradoras de riesgos profesionales (ARP), lo cual mostró el que 98% de los establecimientos no estaban afiliados a una ARP.

Se visitaron 28 sitios de trabajadores independientes con 2,814 personas ubicadas en 1,385 locales, de los cuales 41.5% estaban en el régimen subsidiado. Las actividades económicas predominantes fueron venta de cacharro y lotería.

Se identificaron en la economía informal 5,880 establecimientos, de los cuales se tomó un muestreo del 7% para identificar los riesgos ocupacionales. Se visitaron 205 predios rurales de los cuales 83% estaban en producción agrícola y 17% pecuaria y se hizo en ellos un análisis de riesgos. Se elaboró el mapa de intensidad sonora identificando como áreas más ruidosas la avenida Bolívar, la avenida 14 de octubre y la vía jardines a bosques de pinares” [24].

**Propiciar estilos de vida saludable.** La estrategia de Atención Primaria en Salud tuvo una cobertura de 45 alojamientos y 49 asentamientos temporales, llegando a 9,290 familias con 33,444 personas. Participaron 50 promotoras de salud, 40 técnicos en saneamiento y 10 coordinadores en las gerencias zonales, cuyas funciones fueron identificar el riesgo, canalizar a la atención médica y hacer seguimiento a las familias que vivían en esos alojamientos y asentamientos.

Se llegó a 5,000 familias en estos alojamientos con educación básica en situación de desastres con los componentes de convivencia social y elaboración del duelo, autocuidado y cuidado del ambiente, organización comunitaria y convivencia social; se entregaron insumos básicos para el autocuidado tales como hidratación oral, purgantes, condones, cepillos de dientes, entre otros. Se realizaron talleres de gestión cotidiana del riesgo en las cañadas urbanas.

Se logró la estrategia de pares en adolescentes escolarizados y líderes de alojamientos y asentamientos. Se desarrolló una estrategia para segunda y tercera edad con afiliación al régimen subsidiado de 17,602 personas, atención para la discapacidad de 560 adultos mayores de alojamientos en salud visual y se inició la formación de líderes cuidadores de tercera edad [24].

**Propiciar la participación social.** Se constituyó el Consejo territorial de seguridad social en salud y se puso en funcionamiento el servicio de atención al usuario en la Secretaría de Salud [24]. La gestión del riesgo en salud se llevó a cabo como un proceso de participación social cotidiano que involucró diferentes grupos focales entre los cuales es importante mencionar el sistema alerta – acción con líderes de los asentamientos y los barrios, adolescentes y personas de la tercera edad, para la gestión del riesgo epidemiológico; la gestión del riesgo en las cañadas urbanas con habitantes de estas áreas y ONGs ambientalistas; el trabajo con las ONG de las 15 gerencias zonales para concertar las prioridades de salud pública cuando se constituyó el Forec. Así mismo hubo un grupo focal entre Secretaría Departamental y Secretaría Municipal de Salud.

**Políticas públicas saludables.** Se desarrolló la coordinación interinstitucional y la intersectorialidad con mesas de trabajo para nutrición y seguridad alimentaria, violencia y trauma y el Consejo Físico Ambiental. También se asumieron las competencias entregadas por el Instituto Seccional de Salud del Quindío (ISSQ) en cuanto a vigilancia y control de IPS [24]. 

## 3. CONCLUSIONES

La Secretaría de Salud del Municipio de Armenia ante el terremoto del 25 de enero de 1999 adoptó un modelo de Atención Primaria en Salud al cual denominó Gestión del Riesgo que tenía los componentes de atención a las personas, atención al ambiente, vigilancia en salud pública y educación básica en situación de desastre en el contexto de ciudad educadora. El enfoque de la estrategia fue la gestión cotidiana del riesgo; es decir, el riesgo se identificó tanto en atención a las personas como en atención al ambiente, para analizarlo y buscar alternativas de solución diariamente. Se puede afirmar que al revisar los informes se hacía un análisis de las amenazas y se buscaban alternativas de solución de manera cotidiana, y que se atendieron prioridades en salud pública en cuanto a la salud física y mental de las personas y su convivencia social, así como las prioridades en el ambiente, en agua potable y saneamiento básico.

La fecha del terremoto del eje cafetero antecede a los marcos de referencia vigentes y es posible que los aprendizajes de ese desastre hayan aportado a la actual construcción conceptual y normativa, confirmando que el desastre es siempre una dolorosa oportunidad de aprendizaje y que ese aprendizaje es casi una obligación social para la gestión del riesgo; es por esto que en la conclusión se revisan las lecciones aprendidas en Armenia en el contexto de las prioridades del Protocolo de Sendai.

Prioridad 1: Comprender el riesgo de desastres. En Armenia se trabajó cotidianamente sobre la gestión del riesgo en salud después del desastre.

Prioridad 2: Fortalecer la gobernanza del riesgo de desastres para gestionar dicho riesgo. La estrategia de Atención primaria en Salud permitió que los diferentes actores (instituciones públicas, privadas y ONG de carácter local y nacional) participaran en las áreas de la estrategia tales como atención a las personas, atención al ambiente, vigilancia en salud pública y educación básica en situación de desastre en el contexto de ciudad educadora.

Prioridad 3: Invertir en la reducción del riesgo de desastres para la resiliencia. La Secretaría de Salud y el municipio reorganizaron sus prioridades para la atención del desastre con su personal inicialmente y con coordinación interinstitucional, intersectorial y tempranamente con ayuda de organizaciones nacionales e internacionales. Y posteriormente el nivel nacional organizó el fondo para la reconstrucción con quien se continuó la coordinación.

Prioridad 4: Aumentar la preparación para casos de desastre a fin de dar una respuesta eficaz y para reconstruir mejor en los ámbitos de la recuperación, la rehabilitación y la reconstrucción. El nivel nacional lideró y reorganizó el marco normativo, la política y el sistema de gestión de riesgo de desastres en Colombia.

Si bien el presente trabajo se llevó a cabo para identificar las lecciones aprendidas en Armenia a raíz del terremoto hace 20 años es necesario, ahora que se prepara esta publicación, reconocer a la pandemia por Covid como el mayor desastre registrado hasta ahora por la humanidad, el cual ha puesto en evidencia que el riesgo sigue en ascenso y los patrones de riesgo y desastre son cada vez más complejos, tal como plantea el Informe de evaluación regional sobre el riesgo de desastres en América Latina y el Caribe [25]. Así mismo, como puede verse en la figura el presente desastre ha afectado profundamente a los seres humanos, su salud física y mental, su calidad de vida y su supervivencia a pesar que la infraestructura física continúa en crecimiento.


| PUNTOS CLAVE Cuál es el concepto de gestión del riesgo en salud. Cuáles son las prioridades en gestión del riesgo en salud. Cuál es el marco conceptual y normativo sobre gestión del riesgo en salud en situación de desastres. Cómo fue el manejo del riesgo en salud durante el desastre generado por el terremoto de 1999 en el Municipio de Armenia Quindío. |
| --- |


| PREGUNTAS A RESOLVER En este espacio es importante preguntarse si los aprendizajes que dejó el terremoto del eje cafetero con respecto a la gestión del riesgo en salud pública tienen vigencia frente a los desastres actuales como la pandemia Covid o los patrones de riesgo y desastre son cada vez más complejos que están por venir. |
| --- |

## 4. MATERIALES Y MÉTODOS

Estudio descriptivo de corte, con base en la información generada por la Secretaría de Salud del Municipio de Armenia durante el desastre generado por el terremoto de 1999.

## CONFLICTO DE INTERESES

La autora manifiesta no tener conflicto de intereses

## AGRADECIMIENTOS

A la Secretaría de Salud de Armenia, que permitió la revisión de los informes generados durante el Desastre posterior al terremoto de 1999. A la Organización Panamericana de la Salud (OPS), por su autorización para citar el material de la OPS en el presente documento.

## IDENTIFICACIÓN DE AUTOR

Olga Alicia Nieto-Cárdenas	

## BIBLIOGRAFÍA

Organización Mundial de la Salud. (2002). *Riesgos para la salud. Informe de la salud en el mundo*. OMS Ginebra.

De Almeida, N. Catiel, L.D. & Ayes, J.R. (2009). Riesgo: concepto básico en epidemiología. *Salud colectiva, 5*, 323-344. 

OPS/OMS (Organización Panamericana de la Salud. Organización Mundial de la Salud). (2019, 11 de octubre). *Centro de conocimiento en salud pública y desastres*. 

Resolución 412 de 2000. Ministerio de Salud y Protección Social. Febrero 25 de 2000. Bogotá, D.C.  

Resolución 1841 de 2013. Plan Decenal de Salud 2012-2021. Ministerio de Salud y Protección Social. Mayo 28 de 2013. Bogotá, D.C.  

Ministerio de Salud y Protección Social. (2015). Gestión integral del riesgo en salud. Comité Ampliado. Bogotá, D.C.

Ministerio de Salud y Protección Social. (2008). Sistema de administración de riesgos. Resolución 1740 de 2008. Bogotá, D.C.

Ministerio de Salud y Protección Social (2018). Ruta integral de atención para la promoción y mantenimiento de la salud. Resolución 3280 de 2018. Bogotá, D.C.

Ministerio de Salud y Protección Social. (2019, 4 de noviembre*). Rutas integrales de atención en salud* (RIAS). 

Ministerio de Salud y Protección Social. (2015). *Presentación Rutas Integrales de Atención en Salud (RIAS)*. Bogotá, D.C.

Ley 1523 de 2012. Por la cual se adopta la política nacional de gestión del riesgo de desastres y se establece el Sistema Nacional de Gestión del Riesgo de Desastres y se dictan otras disposiciones. Congreso de Colombia. Abril 24 de 2012. 

Constitución Política de Colombia. Congreso de la República. 1991. Bogotá, D.C.

Gómez, A. (2014). Marco conceptual y legal sobre la gestión del riesgo en Colombia. *Revista Monitor Estratégico, 5*,4-11.

UNDRR (United Nations Office for Disaster Risk Reduction). (2015). *Marco de Sendai para la Reducción del Riesgo de Desastres 2015-2030*. 

Organización Mundial de la Salud. (2016*). Reglamento Sanitario Internacional*. 3ed. OMS. Ginebra.

Organización panamericana de la salud. OPS. (2000). *El impacto de los desastres en la salud pública*. Ed. Noji, E.K. Bogotá, D.C. 

Organización Panamericana de la Salud. Organización Mundial de la Salud. OPS/OMS. (s.f.). *El Agua en situaciones de emergencia*. División de Salud Ambiente. Washington D.C. 

Ministerio de Salud. (2012). *Cartilla ola invernal*. Bogotá, D.C. 

Organización Panamericana de la Salud. (2006*). Guía práctica en situación de desastres. Series manuales y guías sobre desastres No. 7*. J. Rodríguez, M. Zaccarelli & D. Ricardo Pérez (Eds). OPS. Washington D.C.

Organización Panamericana de la Salud (OPS/OMS). (2002). *Protección de la salud mental en situaciones de desastres y emergencias*. Serie de manuales y guías sobre desastres. Washington, D.C.

OPS-OMS (Organización Panamericana de la Salud. Organización Mundial de la Salud).  (2010). *Guía técnica de salud mental en situaciones de desastres y emergencias*. Washington D.C.

Secretaría de Salud de Armenia. (1999). *Perfil de las urgencias atendidas durante el desastre de enero de 1999*. Bedoya, H. Gutiérrez, J.G. Armenia Quindío.

Secretaría de Salud de Armenia. (1999). *Operatividad de la Estrategia de Atención Primaria en Salud*. Armenia.

Secretaría de Salud de Armenia. (1999). *Informe de gestión y resultados 1999*. Armenia Quindío. 

Oficina de las Naciones Unidas para la Reducción del Riesgo de Desastres (UNDRR). (2021). *Informe de evaluación regional sobre el riesgo de desastres en América Latina y el Caribe*.

