# Índice temático {.unnumbered}

Esta página contiene los términos clave utilizados a lo largo del libro con enlaces directos a donde aparecen.

---

## A

- **Adaptación**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Adaptación basada en ecosistemas**: [Capítulo 11](capitulo11-gestion-integral-biodiversidad.qmd), [Capítulo 12](capitulo12-retos-eco-drr-y-sbn.qmd)
- **Adaptación frente al cambio climático**: [Capítulo 11](capitulo11-gestion-integral-biodiversidad.qmd)
- **Afrontamiento**: [Capítulo 15](capitulo15-preparacion-de-respondedores.qmd)
  - Estrategias de afrontamiento
- **Agua potable**: [Capítulo 1](capitulo1-calidad-agua.qmd), [Capítulo 14](capitulo14-gestion-del-riesgo-en-salud.qmd)
- **Aislamiento sísmico**: [Capítulo 10](capitulo10-sistema-control-riesgo-sismico.qmd)
- **Albergues y alojamientos temporales**: [Capítulo 15](capitulo15-preparacion-de-respondedores.qmd)
- **Amenaza en corredores viales**: [Capítulo 3](capitulo3-multiamenaza-corredores-viales.qmd)
  - Por inundación
  - Por movimientos en masa
- **Amenaza por avenidas torrenciales**: [Capítulo 4](capitulo4-avenidas-torrenciales-antioquia.qmd)
- **Amenaza por inundación**: [Capítulo 3](capitulo3-multiamenaza-corredores-viales.qmd), [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
  - Metodología de análisis
- **Amenaza por tsunami**: [Capítulo 2](capitulo2-evaluacion-amenaza-tsunami.qmd)
- **Amenaza sísmica**: [Capítulo 10](capitulo10-sistema-control-riesgo-sismico.qmd)
  - Alta amenaza sísmica en Colombia
  - Comportamiento estructural de nueva infraestructura ante sismos
  - Visión normativa del comportamiento estructural esperado
- **Amenazas antrópicas**: [Capítulo 1](capitulo1-calidad-agua.qmd)
- **Análisis del riesgo por inundación**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Apego al lugar**: [Capítulo 8](capitulo8-percepcion-del-riesgo.qmd)
- **Asentamientos urbanos vulnerables**: [Capítulo 12](capitulo12-retos-eco-drr-y-sbn.qmd)
- **Atención a las personas**: [Capítulo 14](capitulo14-gestion-del-riesgo-en-salud.qmd)
- **Atención Primaria en Salud**: [Capítulo 14](capitulo14-gestion-del-riesgo-en-salud.qmd)
- **Avenidas torrenciales**: [Capítulo 4](capitulo4-avenidas-torrenciales-antioquia.qmd)
  - Amenaza
  - Cálculo de la amenaza
  - Definición
  - Inventario en Antioquia
  - Magnitud
  - Necesidades futuras
  - Ordenamiento territorial
  - Probabilidad temporal
  - Susceptibilidad
  - Tipos
  - Valle de Aburrá

## B

- **Biodiversidad y servicios ecosistémicos**: [Capítulo 11](capitulo11-gestion-integral-biodiversidad.qmd)
- **Biomineralización**: [Capítulo 13](capitulo13-biotratamiento-suelo-quema.qmd)
- **Biotecnología**: [Capítulo 13](capitulo13-biotratamiento-suelo-quema.qmd)
- **Bomberos voluntarios**: [Capítulo 15](capitulo15-preparacion-de-respondedores.qmd)
  - Normativa en Colombia

## C

- **Calidad del agua**: [Capítulo 1](capitulo1-calidad-agua.qmd)
- **Campesinos**: [Capítulo 9](capitulo9-mirada-diferencial-comunidad.qmd)
  - Como concepto en la gestión del riesgo de desastres
- **Capacidad adaptativa**: [Capítulo 11](capitulo11-gestion-integral-biodiversidad.qmd)
- **Captura de datos**: [Capítulo 3](capitulo3-multiamenaza-corredores-viales.qmd)
- **Captura de datos en campo**: [Capítulo 3](capitulo3-multiamenaza-corredores-viales.qmd)
- **Ciencia ciudadana**: [Capítulo 12](capitulo12-retos-eco-drr-y-sbn.qmd)
- **Ciencia, tecnología e innovación**: [Capítulo 3](capitulo3-multiamenaza-corredores-viales.qmd)
- **Comportamiento estructural de nueva infraestructura ante sismos**: [Capítulo 10](capitulo10-sistema-control-riesgo-sismico.qmd)
  - Incoherencias normativas
- **Confianza en las instituciones**: [Capítulo 8](capitulo8-percepcion-del-riesgo.qmd)
- **Conflictos socioecológicos**: [Capítulo 11](capitulo11-gestion-integral-biodiversidad.qmd)
- **Conocimiento de la biodiversidad**: [Capítulo 11](capitulo11-gestion-integral-biodiversidad.qmd)
- **Conocimientos sociales**: [Capítulo 8](capitulo8-percepcion-del-riesgo.qmd)
- **Construcción social del riesgo**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Corredores viales**: [Capítulo 3](capitulo3-multiamenaza-corredores-viales.qmd)
  - Elemento expuesto
  - Fragilidad
  - Inundación
  - Movimientos en masa
  - Resiliencia
  - Vulnerabilidad
  - Vulnerabilidad física
- **Creciente súbita**: [Capítulo 4](capitulo4-avenidas-torrenciales-antioquia.qmd)
  - Definición
- **Curva de Excedencia de Pérdidas**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)

## D

- **Deformación vertical del lecho marino**: [Capítulo 2](capitulo2-evaluacion-amenaza-tsunami.qmd)
- **Desastre de Armero**: [Capítulo 7](capitulo7-desastres-armero-mocoa.qmd)
  - Caracterización del desastre
  - Causas de raíz
  - Condiciones inseguras
  - Presiones dinámicas
- **Desastre de Mocoa**: [Capítulo 7](capitulo7-desastres-armero-mocoa.qmd)
  - Causas raíz
  - Evolución de la tragedia
  - Presiones dinámicas
- **Deslizamientos**: [Capítulo 8](capitulo8-percepcion-del-riesgo.qmd)
- **Dimensión sociocultural**: [Capítulo 8](capitulo8-percepcion-del-riesgo.qmd)
- **Disposición de excretas humanas**: [Capítulo 14](capitulo14-gestion-del-riesgo-en-salud.qmd)

## E

- **Ecosistemas costeros**: [Capítulo 11](capitulo11-gestion-integral-biodiversidad.qmd)
- **Elemento expuesto en corredores viales**: [Capítulo 3](capitulo3-multiamenaza-corredores-viales.qmd)
- **Encuesta de calidad de vida**: [Capítulo 9](capitulo9-mirada-diferencial-comunidad.qmd)
- **Enfoque diferencial**: [Capítulo 9](capitulo9-mirada-diferencial-comunidad.qmd)
- **Enfoque diferencial en la gestión del riesgo de desastres**: [Capítulo 9](capitulo9-mirada-diferencial-comunidad.qmd)
- **Enfoque psicosocial del riesgo**: [Capítulo 8](capitulo8-percepcion-del-riesgo.qmd)
- **Escenarios de riesgo en pérdida de biodiversidad**: [Capítulo 11](capitulo11-gestion-integral-biodiversidad.qmd)
- **Evaluación probabilista de riesgo**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Evolución de la tragedia de Armero**: [Capítulo 7](capitulo7-desastres-armero-mocoa.qmd)
- **Exposición en corredores viales**: [Capítulo 3](capitulo3-multiamenaza-corredores-viales.qmd)
  - Calificación y evaluación

## F

- **Flujo de escombros canalizado**: [Capítulo 4](capitulo4-avenidas-torrenciales-antioquia.qmd)
  - Definición
- **Fragilidad en corredores viales**: [Capítulo 3](capitulo3-multiamenaza-corredores-viales.qmd)
  - Calificación y evaluación
- **Función de vulnerabilidad**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)

## G

- **Gestión del riesgo en salud**: [Capítulo 14](capitulo14-gestion-del-riesgo-en-salud.qmd)
- **Gestión del riesgo por inundación**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Gobernanza del riesgo de desastres**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Guapi**: [Capítulo 2](capitulo2-evaluacion-amenaza-tsunami.qmd)

## I

- **Incendios forestales**: [Capítulo 5](capitulo5-incendios-orinoquia.qmd), [Capítulo 13](capitulo13-biotratamiento-suelo-quema.qmd)
  - Área quemada
  - Biomineralización
  - Biotecnología
  - Características físicas de los suelos
  - Descarga de datos
  - Distribución de las anomalías térmicas
  - FIRMS
  - Focos de calor
  - Google Earth Engine
  - Índice normalizado de área quemada
  - MODIS
  - Pérdida de cobertura vegetal
  - Recuperación de suelos
  - Sentinel-2
  - Suelos degradados
  - Transformación de bosques
- **Indicadores de biodiversidad y servicios ecosistémicos**: [Capítulo 12](capitulo12-retos-eco-drr-y-sbn.qmd)
- **Índice normalizado de área quemada**: [Capítulo 5](capitulo5-incendios-orinoquia.qmd)
  - Cálculo
  - Mapa
- **Índices de pobreza multidimensional**: [Capítulo 9](capitulo9-mirada-diferencial-comunidad.qmd)
- **Infraestructura sismo resistente**: [Capítulo 10](capitulo10-sistema-control-riesgo-sismico.qmd)
  - Cambio de paradigma
  - Hospital seguro
- **Infraestructura vial**: [Capítulo 3](capitulo3-multiamenaza-corredores-viales.qmd)
  - Instrumento de recolección de datos
- **Instrumento móvil de captura de datos**: [Capítulo 3](capitulo3-multiamenaza-corredores-viales.qmd)
- **Inundación de escombros**: [Capítulo 4](capitulo4-avenidas-torrenciales-antioquia.qmd)
  - Definición
- **Inundación en corredores viales**: [Capítulo 3](capitulo3-multiamenaza-corredores-viales.qmd)
- **Inundación lenta**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Inundaciones**: [Capítulo 8](capitulo8-percepcion-del-riesgo.qmd)
- **Inundaciones costeras**: [Capítulo 8](capitulo8-percepcion-del-riesgo.qmd)
- **Inundaciones en ciudades**: [Capítulo 3](capitulo3-multiamenaza-corredores-viales.qmd)
- **Inundaciones lentas o en la llanura**: [Capítulo 3](capitulo3-multiamenaza-corredores-viales.qmd)
- **Inundaciones repentinas**: [Capítulo 3](capitulo3-multiamenaza-corredores-viales.qmd)

## L

- **Litoral Pacífico Colombiano**: [Capítulo 2](capitulo2-evaluacion-amenaza-tsunami.qmd)

## M

- **Manglares**: [Capítulo 11](capitulo11-gestion-integral-biodiversidad.qmd)
- **Máxima amplitud de tsunami**: [Capítulo 2](capitulo2-evaluacion-amenaza-tsunami.qmd)
- **Mitigación del cambio climático**: [Capítulo 11](capitulo11-gestion-integral-biodiversidad.qmd)
- **Mitigación del riesgo sísmico**: [Capítulo 10](capitulo10-sistema-control-riesgo-sismico.qmd)
  - Búsqueda de alternativas
  - Normativa local
  - Normativa para edificaciones con aislamiento de base y disipación de energía para Colombia
- **Modelación hidrológica**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Modelo de exposición**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Modelo *Pressure and Release***: [Capítulo 7](capitulo7-desastres-armero-mocoa.qmd)
  - Metodología
- **Motores de transformación y pérdida de la biodiversidad**: [Capítulo 11](capitulo11-gestion-integral-biodiversidad.qmd)

## O

- **Ordenamiento territorial**: [Capítulo 4](capitulo4-avenidas-torrenciales-antioquia.qmd), [Capítulo 12](capitulo12-retos-eco-drr-y-sbn.qmd)

## P

- **Paradigma psicométrico**: [Capítulo 8](capitulo8-percepcion-del-riesgo.qmd)
- **Percepción del riesgo**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd), [Capítulo 8](capitulo8-percepcion-del-riesgo.qmd)
  - Apego al lugar
  - Confianza en las instituciones
  - Dimensión sociocultural
- **Pérdida Anual Esperada**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Pérdida Máxima Probable**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Perfil epidemiológico**: [Capítulo 14](capitulo14-gestion-del-riesgo-en-salud.qmd)
- **Periodo de retorno**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Política Nacional de Cambio Climático**: [Capítulo 11](capitulo11-gestion-integral-biodiversidad.qmd)
- **Prima Pura de Riesgo**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Prioridades en salud pública**: [Capítulo 14](capitulo14-gestion-del-riesgo-en-salud.qmd)

## R

- **Recuperación de suelos**: [Capítulo 13](capitulo13-biotratamiento-suelo-quema.qmd)
- **Reducción del riesgo de desastres basada en ecosistemas**: [Capítulo 11](capitulo11-gestion-integral-biodiversidad.qmd), [Capítulo 12](capitulo12-retos-eco-drr-y-sbn.qmd)
- **Reforzamiento sísmico y estructural de edificaciones**: [Capítulo 10](capitulo10-sistema-control-riesgo-sismico.qmd)
  - De edificaciones indispensables
- **Reglamento Colombiano de Construcciones Sismo Resistentes NSR-10**: [Capítulo 10](capitulo10-sistema-control-riesgo-sismico.qmd)
- **Relación Media de Daño**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Remoción en masa en corredores viales**: [Capítulo 3](capitulo3-multiamenaza-corredores-viales.qmd)
- **Remoción en masa por inundación**: [Capítulo 3](capitulo3-multiamenaza-corredores-viales.qmd)
- **Resiliencia**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd), [Capítulo 14](capitulo14-gestion-del-riesgo-en-salud.qmd), [Capítulo 15](capitulo15-preparacion-de-respondedores.qmd)
- **Resiliencia en corredores viales**: [Capítulo 3](capitulo3-multiamenaza-corredores-viales.qmd)
  - Calificación y evaluación
- **Respondedores de emergencias**: [Capítulo 15](capitulo15-preparacion-de-respondedores.qmd)
  - Apoyo social
  - Estrés postraumático
  - Resiliencia
- **Restauración ecológica**: [Capítulo 11](capitulo11-gestion-integral-biodiversidad.qmd)
- **Retos**: [Capítulo 12](capitulo12-retos-eco-drr-y-sbn.qmd)
  - Definición
- **Riesgo en epidemiología**: [Capítulo 14](capitulo14-gestion-del-riesgo-en-salud.qmd)
- **Riesgo en la calidad de agua potable**: [Capítulo 1](capitulo1-calidad-agua.qmd)
  - Amenazas
  - Escenarios de análisis
  - Exposición
  - Metodologías
  - Vulnerabilidad
- **Riesgo en sistemas de acueducto**: [Capítulo 1](capitulo1-calidad-agua.qmd)
- **Riesgo sísmico**: [Capítulo 10](capitulo10-sistema-control-riesgo-sismico.qmd)
  - Amenaza sísmica
  - Disipación de energía
  - Nivel de desempeño
- **Rubro de contenidos**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Rubro de edificaciones**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)

## S

- **Salud ambiental**: [Capítulo 14](capitulo14-gestion-del-riesgo-en-salud.qmd)
- **Salud mental en situación de desastre**: [Capítulo 14](capitulo14-gestion-del-riesgo-en-salud.qmd)
- **Sequía**: [Capítulo 8](capitulo8-percepcion-del-riesgo.qmd)
- **Servicios culturales**: [Capítulo 12](capitulo12-retos-eco-drr-y-sbn.qmd)
- **Servicios de aprovisionamiento**: [Capítulo 12](capitulo12-retos-eco-drr-y-sbn.qmd)
- **Servicios de regulación**: [Capítulo 12](capitulo12-retos-eco-drr-y-sbn.qmd)
- **Servicios de soporte**: [Capítulo 12](capitulo12-retos-eco-drr-y-sbn.qmd)
- **Servicios ecosistémicos**: [Capítulo 11](capitulo11-gestion-integral-biodiversidad.qmd), [Capítulo 12](capitulo12-retos-eco-drr-y-sbn.qmd)
  - De regulación
  - Para la reducción del riesgo de desastres
- **Sistema general de seguridad social**: [Capítulo 14](capitulo14-gestion-del-riesgo-en-salud.qmd)
- **Sistemas de acueducto**: [Capítulo 1](capitulo1-calidad-agua.qmd)
  - Amenaza
  - Exposición
  - Vulnerabilidad
- **Sistemas de control de respuesta estructural**: [Capítulo 10](capitulo10-sistema-control-riesgo-sismico.qmd)
  - Activos, semiactivos, pasivos e híbridos
  - Aisladores de base
  - Aplicación
  - Contexto internacional
  - Definición
  - Disipadores de energía o amortiguadores
  - Fabricación local de dispositivos
  - Finalidad
- **Sistemas de información geográfica**: [Capítulo 5](capitulo5-incendios-orinoquia.qmd)
- **Socioecosistema**: [Capítulo 11](capitulo11-gestion-integral-biodiversidad.qmd)
- **Socioecosistemas urbanos**: [Capítulo 11](capitulo11-gestion-integral-biodiversidad.qmd)
- **Soluciones basadas en la naturaleza**: [Capítulo 11](capitulo11-gestion-integral-biodiversidad.qmd), [Capítulo 12](capitulo12-retos-eco-drr-y-sbn.qmd)
  - Análisis costo-beneficio
  - Asentamientos urbanos vulnerables
  - Eco-DRR
  - Financiación de los proyectos
  - Participación ciudadana
  - Pliegos para contratación estatal
  - Procesos de gobernanza inclusivos
  - Soluciones híbridas
  - Toma de decisiones basadas en evidencia
- **Suelos degradados**: [Capítulo 13](capitulo13-biotratamiento-suelo-quema.qmd)
- **Suelos quemados**: [Capítulo 13](capitulo13-biotratamiento-suelo-quema.qmd)
  - Agregación del suelo
  - Consolidación duplo-edométrica
  - Corte directo
  - Curva de retención de agua
  - Curva granulométrica para suelos quemados
  - Desagregación
  - Mineralogía
  - pH y punto de carga zero del suelo
  - Pinhole test

## T

- **Taxonomía de categorías de estructuras de drenaje y estabilización de taludes en corredores viales**: [Capítulo 3](capitulo3-multiamenaza-corredores-viales.qmd)
- **Teledetección**: [Capítulo 5](capitulo5-incendios-orinoquia.qmd)
- **Teledetección de áreas quemadas en la Orinoquía**: [Capítulo 5](capitulo5-incendios-orinoquia.qmd)
- **Tipologías constructivas**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Tipologías estructurales**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Tipos de inundación lenta**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
  - Fluvial o por desbordamiento
  - Pluvial o por encharcamiento
- **Tsunami**: [Capítulo 2](capitulo2-evaluacion-amenaza-tsunami.qmd)
  - Altura máxima
  - Altura máxima de inundación
  - Área de inundación
  - Distancia de inundación
  - Dominio computacional
  - Escenarios sísmicos fuentes
  - Fuente
  - Máxima profundidad
  - Método de simulación numérica y evaluación de la amenaza
  - Modelo
  - Modelo de deslizamiento interplaca
  - Profundidad de inundación
  - Propagación
  - SATREPS
  - Simulación

## V

- **Valor económico y población expuesta**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Valor expuesto**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Valoración de la amenaza por inundación**: [Capítulo 3](capitulo3-multiamenaza-corredores-viales.qmd)
- **Velocidad media de flujo**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Vida digna**: [Capítulo 9](capitulo9-mirada-diferencial-comunidad.qmd)
  - Derecho a una vida digna
- **Vigilancia en salud pública**: [Capítulo 14](capitulo14-gestion-del-riesgo-en-salud.qmd)
- **Vulnerabilidad de campesinos**: [Capítulo 9](capitulo9-mirada-diferencial-comunidad.qmd)
- **Vulnerabilidad del rubro de edificaciones**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Vulnerabilidad en corredores viales**: [Capítulo 3](capitulo3-multiamenaza-corredores-viales.qmd)
- **Vulnerabilidad física**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Vulnerabilidad física en corredores viales**: [Capítulo 3](capitulo3-multiamenaza-corredores-viales.qmd), [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)
- **Vulnerabilidad frente al cambio climático**: [Capítulo 11](capitulo11-gestion-integral-biodiversidad.qmd)
- **Vulnerabilidad psicológica**: [Capítulo 15](capitulo15-preparacion-de-respondedores.qmd)
- **Vulnerabilidad social**: [Capítulo 6](capitulo6-riesgo-inundacion-mojana.qmd)

## Z

- **Zoonosis**: [Capítulo 14](capitulo14-gestion-del-riesgo-en-salud.qmd)

---

**Nota**: En la versión PDF del libro encontrará un índice temático completo con números de página al final del documento.
