# Lista de pares revisores {.unnumbered}

**Jesús Adolfo Anaya Acevedo** | Universidad de Medellín, Colombia

**Arlex Angarita Leiton** | Corporación Universitaria Minuto de Dios – UNIMINUTO, Colombia

**Rafael Aránguiz Muñoz** | Universidad Católica de la Santísima Concepción, Chile

**César Camilo Cañón Barriga** | Pontificia Universidad Javeriana, Colombia

**Carlos Andrés Caro Camargo** | Universidad Santo Tomás, Colombia

**Saieth Baudilio Chaves Pabón** | Universidad Militar Nueva Granada, Colombia

**Claudia Patricia Coca Galeano** | Candidata a PhD en Ciencias Humanas y Sociales, CES - Universidad Nacional de Colombia

**Alejandra María Díaz Tamayo** | Universidad del Valle, Colombia

**Ignacio Escuder Bueno** | Universidad Politécnica de Valencia, España

**Carolina García Londoño** | Sociedad Colombiana de Geología, Presidente Capítulo Antioquia, Colombia

**Cesar Ignacio Garay Bohorquez** | Fondo para la Acción Ambiental y la Niñez, Colombia

**María Mercedes Gonzalez** | Universidad del Quindío, Colombia

**Helbert García-Delgado** | Syracuse University, USA

**Yesid Paul Goyes Peñafiel** | Universidad Industrial de Santander, Colombia

**Sthefania Grajales Noreña** | CIMNE, Ingeniar - Risk Intelligence, Colombia

**Yolanda Teresa Hernandez Peña** | Universidad Distrital Francisco José de Caldas, Colombia

**Carmen Lacambra S.** | Grupo LaEra, Director de investigación y línea de soluciones ambientales, Colombia

**Paula Andrea Lara Ramírez** | Universidad de Antioquia, Facultad Nacional de Salud Pública, Colombia

**Víctor Leonardo López J**. | Universidad de la Salle, Colombia

**Marina Begoña Martínez González** | Universidad de la Costa, Colombia

**Vladimir Ernesto Merchan Jaimes** | Universidad Industrial de Santander, Colombia

**Laura L. Pirazán Palomar** |TH Köln – University of Applied Sciences, Alemania

**Alejandro Ramirez Madrigal** | Institución Universitaria Visión de las Américas, Colombia

**Antonio Andrés Reyes Merchán** | Servicio Geológico Colombiano, Dirección de Geoamenazas, Colombia

**Rafael Andrés Muñoz Quintero** | Consultoría y Gestión Ambiental S.A.S y Universidad de Los Andes, Colombia

**Wilson A. Ramírez H**. | Investigador Instituto Humboldt, Asesor Ministro, Colombia

**Luz Angela Rojas Bernal** | Fundación Universitaria del Área Andina, Colombia

**Mauricio Romero Torres** | Unidad Nacional de Gestión del Riesgo de Desastres, Colombia

**Willian Sierra Barón** | Universidad Surcolombiana, Colombia

**Oscar David Sierra Guzmán** | Enfermero, Universidad Nacional de Colombia

**Jenny M. Trilleras Motha** | Profesional independiente, Colombia

**Jairo Andrés Valcárcel Torres** | Universidad de La Salle, Facultad de Ingeniería, Colombia

**Joaquín Andrés Valencia Ortiz** | Universidad Industrial de Santander, Colombia

**Amanda Varela Ramírez** | Pontificia Universidad Javeriana, Colombia

**Erick R. Velasco-Reyes** | Universidad de Tohoku, Japón

**Carolina S. Velásquez Calderón** | PhD, Gestión y Ciencia de los Desastres, Unidad Nacional para la Gestión del Riesgo de Desastres, Colombia

**Paula Andrea Villegas González** | Pontificia Universidad Javeriana, DGIRH del Ministerio de Ambiente y Desarrollo Sostenible, Colombia

