lang: es
project:
  type: book

book:
  title: "Investigaciones en Gestión del Riesgo de Desastres para Colombia del 2023"
  repo-url: https://github.com/scr-ungrd/investigaciones-grd-2023
  repo-actions: [source, issue]
  sidebar:
    logo: media/UNGRD-Horizontal.png
  chapters:
    - index.qmd
    - 00-01-presentacion.qmd
    - 00-02-pagina-legal.qmd
    - 00-03-4-prologo-del-libro-grd-2022.qmd
    - capitulo1-calidad-agua.qmd
    - capitulo2-evaluacion-amenaza-tsunami.qmd
    - capitulo3-multiamenaza-corredores-viales.qmd
    - capitulo4-avenidas-torrenciales-antioquia.qmd
    - capitulo5-incendios-orinoquia.qmd
    - capitulo6-riesgo-inundacion-mojana.qmd
    - capitulo7-desastres-armero-mocoa.qmd
    - capitulo8-percepcion-del-riesgo.qmd
    - capitulo9-mirada-diferencial-comunidad.qmd
    - capitulo10-sistema-control-riesgo-sismico.qmd
    - capitulo11-gestion-integral-biodiversidad.qmd
    - capitulo12-retos-eco-drr-y-sbn.qmd
    - capitulo13-biotratamiento-suelo-quema.qmd
    - capitulo14-gestion-del-riesgo-en-salud.qmd
    - capitulo15-preparacion-de-respondedores.qmd
    - 99-01-7-lista-pares-revisores-lgrd-2022.qmd
    - 99-02-al-final-indice-tematico.qmd

format:
  html:
    theme: 
      - lumen
      - theme.scss
    css: custom.css
    toc: true
    toc-depth: 4
    toc-expand: true
    number-sections: false
    html-math-method: mathjax
    reader-mode: true
    page-navigation: true
    back-to-top-navigation: true
