project:
  type: book
  output-dir: _book

book:
  title: "Investigaciones en Gestión del Riesgo"
  sidebar:
    logo: media/Logo-UNGRD-Horizontal-removebg-preview.png
  chapters:
    - index.qmd
    - 00-02-pagina-legal.qmd
    - 00-03-4-prologo-del-libro-grd-2022.qmd
    - 01-c01-lgrd-14-calidad-agua-vf-2022-08-17.qmd
    - 02-c02-lgrd-16-evaluacion-amenaza-tsunami_vf-202.qmd
    - 03-c3-lgrd-27-multiamenaza-corredores-vialesvf20.qmd
    - 04-c04-lgrd-15-avenidas-torrenciales-antioquia_v.qmd
    - 05-c5-lgrd-12-incendios-orinoquiavf-2022-09-26.qmd
    - 06-c06-lgrd-23-riesgo-inundacion-mojana-vf-2022-.qmd
    - 07-c07-lgrd-07-desastres-armero-mocoavf-2022-09-.qmd
    - 08-c08-lgrd-20-percepcion-del-riesgovf-2-2022-08.qmd
    - 09-c9-lgrd-18-mirada-diferencial-comunidad-vf-20.qmd
    - 10-c10-lgrd-19-sistema-control-riesgo-sismico-vf.qmd
    - 11-c11-lgrd-06-gestion-integral-biodiversidadv6-.qmd
    - 12-c12-lgrd-21-retos-eco-drr-y-sbn-vf-2022-18-08.qmd
    - 13-c13-lgrd-10-biotratamiento-suelo-quema-19-09-.qmd
    - 14-c14-lgrd-03-gestion-del-riesgo-en-salud-vf-v4.qmd
    - 15-c-15-lgrd-11-preparacion-de-respondedores-vf3.qmd
    - 99-01-7-lista-pares-revisores-lgrd-2022.qmd
    - 99-02-al-final-indice-tematico.qmd

format:
  html:
    theme: 
      - lumen
      - theme.scss
    css: styles.css
    toc: true
    toc-depth: 4
    toc-expand: true
    number-sections: false
    html-math-method: mathjax
    reader-mode: true
    page-navigation: true
    back-to-top-navigation: true
