# **LISTA DE AUTORES**

**Sandra Eliana Alzate Vargas |** Facultad de Derecho y Ciencias Políticas, Grupo Estudios de Derecho y Política. Universidad de Antioquia, Medellín, Colombia

   
**María Isabel Arango Carmona |** Departamento de Geociencias y Medio Ambiente. Universidad Nacional de Colombia, sede Medellín, Colombia

   
**Joan Sebastián Arbeláez Caro |** Universidad de San Buenaventura Medellín, extensión Armenia, Colombia

   
**Julián Darío Arbeláez Salazar |** Unidad Nacional para la Gestión del Riesgo de Desastres (UNGRD). Instituto de Hidrología, Meteorología y Estudios Ambientales (IDEAM). Universidad de los Andes, Facultad de Ingeniería, Bogotá, D.C., Colombia

   
**Edier Aristizábal |** Departamento de Geociencias y Medio Ambiente. Universidad Nacional de Colombia, sede Medellín, Colombia

   
**Fabián Mauricio Caicedo Carrascal |** Unidad Nacional para la Gestión del Riesgo de Desastres (UNGRD). Instituto de Hidrología, Meteorología y Estudios Ambientales (IDEAM). Pontificia Universidad Javeriana, Facultad de Ingeniería, Bogotá, D.C., Colombia

   
**José Camapum de Carvalho |** Doctor en Geotecnia, Profesor Titular, Universidad de Brasilia, Brasil

   
**Dorotea Cardona Hernández |** Instituto de Investigación de Recursos Biológicos Alexander von Humboldt. Programa de Gestión Territorial de la Biodiversidad, Bogotá, D.C, Colombia

   
**Laura Vanessa Corrales Brand |** Universidad de San Buenaventura, Medellín, Colombia

   
**Lina Dorado González |** Unidad Nacional para la Gestión del Riesgo de Desastres (UNGRD), Bogotá, D.C., Colombia

   
**Sandra Patricia Duque Quintero |** Facultad de Derecho y Ciencias Políticas, Grupo Estudios de Derecho y Política. Universidad de Antioquia, Medellín, Colombia

   
**María Angela Echeverry-Galvis |** Facultad de Estudios Ambientales y Rurales, Pontificia Universidad Javeriana, Bogotá, D.C., Colombia

   
**Juan Sebastián Echeverry |** Centro de Investigación en Materiales y Obras Civiles, Departamento de Ingeniería Civil y Ambiental, Universidad de los Andes. Bogotá, D.C., Colombia

   
**Julián Alberto Espejo-Díaz |** Facultad de Ingeniería, Universidad de La Sabana, Chía, Colombia

   
**Rafael Fernández |** Centro de Investigación en Materiales y Obras Civiles, Departamento de Ingeniería Civil y Ambiental, Universidad de los Andes. Bogotá D.C., Colombia


**Daniel Ruiz Figueroa |** Centro de Investigaciones Oceanográficas e Hidrográficas del Pacífico (CCCP), Área de Manejo Integrado de Zona Costera, Tumaco, Colombia

   
**Juan Pablo Forero Acevedo |** Unidad Nacional para la Gestión del Riesgo de Desastres (UNGRD). I+R Consultores en Ingeniería y Riesgos S.A.S, Bogotá, D.C., Colombia

   
**Carolina García Londoño |** Sociedad Colombiana de Geología (SCG), Capítulo Antioquia, Medellín, Colombia

   
**Iván Alejandro Giraldo |** Centro de Investigación en Ingeniería Ambiental, Departamento de Ingeniería Civil y Ambiental, Universidad de los Andes. Bogotá, D.C., Colombia

   
**Federico Gómez Cardona |** Departamento de Geociencias y Medio Ambiente. Universidad Nacional de Colombia, sede Medellín, Colombia

   
**William J. Guerrero |** Facultad de Ingeniería, Universidad de La Sabana, Chía, Colombia

   
**Maykel Yisseth Gutiérrez |** Unidad Nacional para la Gestión del Riesgo de Desastres (UNGRD). Bogotá, D.C., Colombia

   
**Diego Gutiérrez |** Empresa de Acueducto y Alcantarillado de Bogotá EAAB-ESP, Dirección Ingeniería Especializada. Bogotá, D.C., Colombia

   
**Luis Augusto Lara-Valencia |** Doctor en Estructuras, Profesor Asociado, Universidad Nacional de Colombia, sede Medellín, Colombia

   
**Mildred Lemus |** Centro de Investigación en Ingeniería Ambiental, Departamento de Ingeniería Civil y Ambiental, Universidad de los Andes, Bogotá, D.C., Colombia

   
**Nubia León |** Empresa de Acueducto y Alcantarillado de Bogotá EAAB-ESP, Dirección Ingeniería Especializada, Bogotá, D.C., Colombia

   
**Juliana Martínez |** Centro de Investigación en Ingeniería Ambiental, Departamento de Ingeniería Civil y Ambiental, Universidad de los Andes, Bogotá, D.C., Colombia

   
**Alejandro Marulanda Tobón |** Escuela de Ciencias, Departamento de Ciencias Físicas, Universidad EAFIT, Medellín, Colombia

   
**Luz Adriana Muñoz-Duque |** Grupo de Investigación en Psicología Sociedad y Subjetividades, Facultad de Ciencias Sociales y Humanas, y Grupo de Investigación Salud y Ambiente, Facultad Nacional de Salud Pública, Universidad de Antioquia, Medellín, Colombia

   
**Óscar E. Navarro Carrascal |** Profesor de Psicología Social y Ambiental, Universidad de Nîmes, Francia. Presidente de la Asociación Francesa de Psicología Ambiental, ARPEnv

**Olga Alicia Nieto Cárdenas |** Programa de Medicina. Facultad de Ciencias de la Salud. Universidad del Quindío, Armenia, Colombia

   
**Juan Camilo Olaya González |** Unidad Nacional para la Gestión del Riesgo de Desastres (UNGRD). I+R Consultores en Ingeniería y Riesgos S.A.S., Bogotá, D.C., Colombia

   
**Carlos Oliveros |** Centro de Investigación en Materiales y Obras Civiles, Departamento de Ingeniería Civil y Ambiental, Universidad de los Andes, Bogotá, D.C., Colombia

   
**Adriana Osorio Mosquera |** Facultad de Ingeniería, Tecnológico de Antioquia – Institución Universitaria, Medellín, Colombia

   
**Valentina Ospina Poveda |** Universidad de San Buenaventura, Medellín, Colombia

   
**Lina Ospina Ostios |** Escuela de Ingeniería Civil y Geomática (EICG), Universidad del Valle, Calí, Colombia

   
**Olga Liliana Pineda López |** Universidad de San Buenaventura Medellín, extensión Armenia, Colombia

   
**Juan Andrés Oviedo Amezquita |** efe-Prima-ce Control y Diseño de estructuras SAS, Medellín, Colombia

   
**Jhonatan Cristian Paz Quintero |** Centro de Investigaciones Oceanográficas e Hidrográficas del Pacífico (CCCP), Área de Manejo Integrado de Zona Costera, Tumaco, Colombia

   
**Carlos Mario Piscal Arevalo |** Universidad de La Salle, Programa de Ingeniería Civil, Bogotá, D.C., Colombia. Red Colombiana de Investigación en Ingeniería Sísmica (CEER)

   
**Lina Porras |** Centro de Investigación en Ingeniería Ambiental, Departamento de Ingeniería Civil y Ambiental, Universidad de los Andes, Bogotá, D.C., Colombia

   
**Luz Stela Quintana Hernández |** Universidad de San Buenaventura Medellín, extensión Armenia, Colombia

   
**Paola Andrea Quintero Rodríguez |** Centro de Investigaciones Oceanográficas e Hidrográficas del Pacífico (CCCP), Área de Manejo Integrado de Zona Costera, Tumaco, Colombia

   
**Fabio Hernán Realpe Martínez |** Centro de Investigaciones Oceanográficas e Hidrográficas del Pacífico (CCCP), Área de Manejo Integrado de Zona Costera, Tumaco, Colombia

   
**Juan Carlos Reyes |** Centro de Investigación en Materiales y Obras Civiles, Departamento de Ingeniería Civil y Ambiental, Universidad de los Andes. Bogotá, D.C., Colombia

**Constanza Ricaurte-Villota |** Programa de Geociencias Marinas y Costeras (GEO). Instituto de Investigaciones Marinas y Costeras “José Benito Vives de Andréis” INVEMAR, Santa Marta, Colombia

   
**Diana M. Rodríguez-Coca |** College of Engineering, Architecture and Technology Oklahoma State University, United States of America

   
**Manuel Rodríguez Susa |** Centro de Investigación en Ingeniería Ambiental, Departamento de Ingeniería Civil y Ambiental, Universidad de los Andes. Bogotá, D.C., Colombia

   
**Mauricio Romero-Torres |** Unidad Nacional para la Gestión del Riesgo de Desastres, Subdirección para el Conocimiento del Riesgo, Bogotá, D.C., Colombia

   
**Ronald Efrén Sánchez Escobar |** Centro de Investigaciones Oceanográficas e Hidrográficas del Pacífico (CCCP), Área de Manejo Integrado de Zona Costera, Tumaco, Colombia

   
**José Ville Triana García |** Unidad Nacional para la Gestión del Riesgo de Desastres (UNGRD). Instituto de Hidrología, Meteorología y Estudios Ambientales (IDEAM). Universitët Salzburg. Salzburgo (Austria)

   
**Daniela Torinjano Jiménez |** Facultad de Ingeniería, Tecnológico de Antioquia – Institución Universitaria, Medellín, Colombia

   
**Jairo Andrés Valcárcel Torres |** Unidad Nacional para la Gestión del Riesgo de Desastres (UNGRD). Universidad de La Salle, Facultad de Ingeniería. Bogotá, D.C., Colombia

   
**Yamile Valencia-González |** Doctora en Geotecnia, Profesora Asociada, Universidad Nacional de Colombia, sede Medellín, Colombia

   
**Paula Andrea Villegas González |** Unidad Nacional para la Gestión del Riesgo de Desastres (UNGRD). Pontificia Universidad Javeriana, Facultad de Ingeniería, Bogotá, D.C., Colombia

   
**Carla María Zapata Rueda |** Universidad de San Buenaventura, Medellín, Colombia

